### ISSUE TITLE
Meta Class Overriding is not working 

### ISSUE THREAD

**Issue by farhankn** [django-import-export/django-import-export#1000]
Hi.
I'm using Django 2.1, and Admin Import to import data,

In **admin.py**
```
class app_detailsResource(resources.ModelResource):
    class Meta:
        model = app_details
        import_id_fields = ['appId_date']
        skip_unchanged = True
        report_skipped = True
```

The application throws error and it checks for id field. 
I have tried, adding an empty id field. 

When I am trying to make changes in /site-packages/import-export/resources.py it works.
Could you please let me know what the error is?

**Comment by ababic** [comment]
Hi @farhankn. Could you share the stack trace, so that we can see where the error is occurring? 

There are unit tests showing that this feature works, but `appId_date` must be a field on the `app_details` model, and there also must be a column with the header `appId_date` in the uploaded dataset in order for this to work. Can you confirm both of those things are in place?

**Comment by ababic** [comment]
Did you also set the `resource_class` attribute on your `ModelAdmin` class to this one? It sounds like a resource might still be being created automatically from the model.

**Comment by farhankn** [comment]
Hi, I have fixed it,
I was not instantiating the class inside the model. So, overriding was not working.

Thanks
