### ISSUE TITLE
Problem importing excel with formulas

### ISSUE THREAD

**Issue by light1988** [django-import-export/django-import-export#1003]
I've found that there is a problem when you try to import an excel with formulas.

If you use and .xls file it works fine but, if the file is and .xlsx, it reads formulas and not values.

Could it be a bug?

Tested with:
```
python: 3.7.4
django: 2.2.5
django-import-export: 1.2.0
```

**Comment by light1988** [comment]
Does anyone know anything about this?

**Comment by andrewgy8** [comment]
This sounds more like a tab lib issue more than a Django-import-export issue. Have you tried using tablib directly to see if it works?

**Comment by light1988** [comment]
No, i didn't. I will check it out. Thanks.

**Comment by matthewhegarty** [comment]
I could reproduce as follows

- In admin site, export book as xlsx
- Open the downloaded file and change an author cell to ABS(5) - swap in the actual value of the cell here
- Save and import the file
- It will give an error showing that the formula and not the value is to be imported (see attached)

Apparently can be fixed with `data_only` flag (#1095).

![error1](https://user-images.githubusercontent.com/6249838/131325774-2c99466b-5630-42f5-87a9-e8d8145d23c4.png)
