### ISSUE TITLE
MySQLOperationalError: 1267 when imports m2m field that contain emoji

### ISSUE THREAD

**Issue by RyanLoil** [django-import-export/django-import-export#1044]
got an error : MySQLdb._exceptions.OperationalError: (1267, "Illegal mix of collations (utf8mb4_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")

this error will show up when the m2m field has emoji. This kind of emoji somehow is somekind of Chinese code format.
For example: 💋,💍,🍊

Environment:
Django 2.2.6
Python 3.8.0
import-export 1.2.0
MySQL mysqlnd 5.0.12

**Comment by claudep** [comment]
This has nothing to do specifically with django-import-export, this is a database configuration issue. You should convert your tables to utf8mb4, as some emojis use four-bytes Unicode characters.

**Comment by 1171000408** [comment]
Thank you for replying! 
I've already taken this into account. My database's table is set as uft8mb4_bin,and as far as i'm concerned, this problem's caused by this kind of emojis using "=" characters as their prefix, which django-import-export recognized them as boolean comparators rather than ​strings. I've tried utf8mb4 format, it happened again.


> This has nothing to do specifically with django-import-export, this is a database configuration issue. You should convert your tables to utf8mb4, as some emojis use four-bytes Unicode characters.

**Comment by claudep** [comment]
Interesting... maybe you could provide a full traceback so as we can see where the error happens. Did you try to reproduce with a different database?

**Comment by 1171000408** [comment]
I'll provide you the full traceback when I get back to my company HQ(I'm on vacation, so sorry, data cannot be transfer by the Internet). By the way, not all emoji have this kind of problem, only some Chinese emoji which utf8 is supported. 
Somehow I think the key to the problem is that django-import-export use "=" to match the m2m field data, when there is another "=", the program recognizes it wrongly;
Or when these emoji show up, django-import-export recognizes them as utf8_general_ci, and this format cannot be conpared by utf8mb4.

**Comment by matthewhegarty** [comment]
Parsing files was refactored in #1306 - if you can reproduce with latest version, please comment and we will look into it.
