### ISSUE TITLE
Setting fields to be excluded in during validation

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1051]
During validation, `full_clean()` is [called](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L299).  Excluded fields are set to those which have already generated errors.

This means that the user has no control over which fields on the model are excluded from validation.  Perhaps there should be a meta attribute `validation_exclude_fields` which enables the user to specify which fields to exclude, and this set could be joined with the `error.keys()` set.

If this feature is of interest I can send a PR

**Comment by qagren** [comment]
In addition to this, I think that passing `list(errors)` to `validate_unique()` rather than `errors.keys()` would be a better choice, since code that tampers with `exclude` in `validate_unique()` probably expects it to be a list rather than an immutable `dict_keys` instance. For example, the following code would break:
```python
def validate_unique(self, exclude=None):
  exclude = exclude or []
  exclude += ['myattribute']
  super().validate_unique(exclude)
```

**Comment by matthewhegarty** [comment]
Closing - no likely progress on this in near future.
