### ISSUE TITLE
I can't import comma listed string into Django-taggit tags using Django-import-export. 

### ISSUE THREAD

**Issue by Spacekoki** [django-import-export/django-import-export#1058]
I can't import Django-taggit tags using Django-import-export. 

This error is when value is entered.

`Line number: 1 - invalid literal for int() with base 10: 'def'`

Also, this error is when the value is blank.

`Line number: 2 - Cannot add <QuerySet []> (<class 'django.db.models.query.QuerySet'>). Expected <class 'django.db.models.base.ModelBase'> or str.`

**xlsx table**　

id | author | title | text | file | free_tags 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1 | 5 | abc | hello |  | def,ghi 
2 | 5 | oh | yeah | | 

**models.py**
```
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager

class KnowHow(models.Model):    

    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField(blank=True)
    file = models.FileField(blank=True,upload_to='explicit_knowhows')
    free_tags = TaggableManager(blank=True)
    
    def __str__(self):
        return self.title
```
**admin.py**
```
from django.contrib import admin
from import_export import resources
from import_export import fields
from import_export.admin import ImportExportModelAdmin

from .models import KnowHow

class KnowHowResource(resources.ModelResource):

    class Meta:
        model = KnowHow
        import_id_fields = ['id']

@admin.register(KnowHow)
class knowHowAdmin(ImportExportModelAdmin):
    resource_class = KnowHowResource
```

**Comment by matthewhegarty** [comment]
Try declaring the field in `KnowHowResource` ([docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#declaring-fields)):

```python
class KnowHowResource(resources.ModelResource):
    free_tags = fields.Field(attribute="free_tags", column_name="free_tags", widget=widgets.CharWidget())
    ...
```
You can also specify a [default value](https://django-import-export.readthedocs.io/en/latest/api_fields.html#fields) which may get you past the empty string issue.

I don't know how django-taggit works but you may have to write your own custom widget so that the comma-delimited values get parsed into the format required by `TaggableManager`.

**Comment by Spacekoki** [comment]
I did like this, and I successfully imported, but tags were not added to taggit and also, it was not related to articles. 
```
from django.contrib import admin
from import_export import resources
from import_export import fields,widgets
from import_export.admin import ImportExportModelAdmin

from .models import KnowHow
# Register your models here.

class KnowHowResource(resources.ModelResource):

    free_tags = fields.Field(attribute="free_tags", column_name="free_tags", widget=widgets.CharWidget())

    class Meta:
        model = KnowHow
        import_id_fields=['id']


#admin.site.register(KnowHow)
@admin.register(KnowHow)
class knowHowAdmin(ImportExportModelAdmin):
    resource_class = KnowHowResource
```

**Comment by matthewhegarty** [comment]
Looking at the `django-taggit` docs, I think that the issue is that you have to use their supplied [API](https://django-taggit.readthedocs.io/en/latest/api.html).

For example:
```python
>>> apple.tags.all()
[<Tag: red>, <Tag: green>, <Tag: delicious>]
```

`django-import-export` won't know how to do this because it knows nothing about the `django-taggit` API.  

I think you would need to create a subclass of [Field](https://django-import-export.readthedocs.io/en/latest/api_fields.html) (e.g. 'TaggitField').  Have a look at the `Field` source, I think you would need to override the [save()](https://github.com/django-import-export/django-import-export/blob/master/import_export/fields.py#L101) method, so that you use the `django-taggit` API appropriately when saving.  Depending on your use cases, this could involve removing / adding tags.

Then obviously you will use your `TaggitField` in the `KnowHowResource` declaration:

```python
class KnowHowResource(resources.ModelResource):

    free_tags = fields.TaggitField(attribute="free_tags", column_name="free_tags", widget=widgets.CharWidget())

```

**Comment by Spacekoki** [comment]
Ok. I got it. I will try it. I'm bigger so, let me review it. 
I only need to import and add tags.
In the save() method,  I have to split _self_ with ',' and run obj.free_tags.add().
Is this right?
Forgive for my poor English.

**Comment by Spacekoki** [comment]
I'm a beginner so could you teach me how to do that?
I copied  [fields.py](https://github.com/django-import-export/django-import-export/blob/master/import_export/fields.py) to my app and renamed TaggitField.py and renamed class into TaggitField.
And I changed [this line](https://github.com/django-import-export/django-import-export/blob/master/import_export/fields.py#L5) to `from import_export import widgets`.
I don't know what to write inside save() method.

**Comment by matthewhegarty** [comment]
The best way to learn is to read through the documentation and code yourself and try to understand what's going on.  As a beginner, it's better to post on Stack Overflow, rather than here, which is better for issues related to `django-import-export`.

You don't need to copy `fields.py`, you only need to override a single method in the class.

Also, if you use [`SimpleArrayWidget`](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L253) then that will take care of splitting the string.

So I think all you need is:

```python
class TaggitField(fields.Field):
    """
    Custom field to add a list of strings (tags) to a TaggableManager instance.
    """
    def save(self, obj, data, is_m2m=False):
        if not self.readonly:
            attrs = self.attribute.split('__')
            for attr in attrs[:-1]:
                obj = getattr(obj, attr, None)
            # this will be list of strings (returned by SimpleArrayWidget.clean())
            cleaned = self.clean(data)
            if cleaned is not None or self.saves_null_values:
                # overridden logic is here
                getattr(obj, attrs[-1]).add(*cleaned)


class KnowHowResource(resources.ModelResource):

    free_tags = TaggitField(attribute="free_tags", column_name="free_tags", widget=widgets.SimpleArrayWidget())
```
I haven't tested this so don't rely on it until you have tested thoroughly and make sure you understand what's going on.

**Comment by Spacekoki** [comment]
Thanks.
I tested it, It successfully imported, but there was an error like this.
```
KnowHow objects need to have a primary key value before you can access their tags.
```
I read [this stackoverflow](https://stackoverflow.com/questions/5546485/django-taggit-error-mydata-objects-need-to-have-a-primary-key-value-before-yo)
So, I first exclude free_tags  and import data to create models, then I imported again so that I can add tags, but I got an error like this.
```
Exception Value: '_TaggableManager' object is not iterable
```

**Comment by matthewhegarty** [comment]
`TaggableManager` is implemented as a [many-to-many field](https://github.com/jazzband/django-taggit/blob/master/taggit/managers.py#L387), therefore you should use a [`ManyToManyWidget`](https://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.ManyToManyWidget), which is designed to handle this relationship:

```python
 free_tags = TaggitField(attribute="free_tags", column_name="free_tags", widget=widgets.ManyToManyWidget())
```

This means that the m2m relations get [saved after the initial import](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L528), so it means you don't have to import twice.

Also, I noticed that `django-taggit` provides a `set()` method in the [API](https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager.set), so this means that you don't need to subclass Field (as described [here](https://github.com/django-import-export/django-import-export/issues/1058#issuecomment-570816419)).

Hopefully using `ManyToManyWidget` will solve the issue for you, but you may need to read the code / docs some more.  It's useful to step through with a debugger if you are not already doing so.

**Comment by Spacekoki** [comment]
I did like this:
```python
free_tags = fields.Field(attribute="free_tags", column_name="free_tags", widget=widgets.ManyToManyWidget(KnowHow.free_tags))
```
But thre was an error :
```
 '_TaggableManager' object has no attribute 'objects'
```

**Comment by matthewhegarty** [comment]
I think your widget needs to receive the Model (`KnowHow`) not the model attribute.

From now, I suggest studying the code / docs to figure out the error.  As a beginner you will learn a lot from this process.  If you have further questions, please post to Stack Overflow.

**Comment by Spacekoki** [comment]
Okay. Thank you for helping me.
By the way, I have already done with `KnowHow`, but the error was same.
I posted to [stackoverflow](https://stackoverflow.com/questions/59606416/django-taggit-import-export-i-had-an-error-taggablemanager-object-has-no-a) .
