### ISSUE TITLE
Integrity error and Null-able fields

### ISSUE THREAD

**Issue by avorio** [django-import-export/django-import-export#1089]
I just noticed that even though my Model defines a `null=False, blank=False` field, django-import-export by default will not handle empty strings in the CSV dataset and ends up causing integrity errors in the database by creating objects with empty or null fields. My whole app broke because of this. I was expecting it to throw an exception or something at the import process.

What am I not seeing here? Any pointers?

Many thanks.

**Comment by pokken-magic** [comment]
From what I can tell, Django appears to let you set empty strings - the "blank=False" controls forms behavior, not database behavior. And if you have a charfield or text field, it should send ''. 

So with null=False and blank=False, empty string fields that are char/text fields should always end up as empty strings in the DB. Django import-export uses the model (and model manager for bulk) methods for persisting data, so will not honor blank=False as far as I am aware. You can add validators that should be honored. 

Can you clarify a few things? 

* What version of Django are you running?
* What exactly was the behavior, with a sample dataset if possible? 
* What types of fields ended up as nulls vs. empty strings?

--

Looking at the code, it looks to me like the Field class is where most of this is controlled (with a Widget sometimes interacting depending on how it cleans). 

When persisting/cleaning a field, it:
1) cleans it with the widget's clean method
2) checks to see if the value is in empty values (None or empty string) and you provided a default, it calls the default or provides it if it's not callable
3) Returns the value

So if you provide an empty string, it will try to save an empty string, unless you provide a default. 

The two potential problems I could see that could cause inconsistent behavior are:
1) If there is a bug in the CSV loader that interprets empty strings wrong 
2) If there is a bug in whatever widget got selected that causes it to provide Nones instead of ''s

However, if you have Null=False in the django field, you should not be able to save a model with a null field. 

If this is still an issue and you can clarify the behavior I'm happy to look into it!

**Comment by matthewhegarty** [comment]
> If there is a bug in whatever widget got selected that causes it to provide Nones instead of ''s

This was the case in `CharWidget` and there is a workaround to address this added [here](https://github.com/django-import-export/django-import-export/pull/1623).
