### ISSUE TITLE
How to dynamically add fields in the export file?

### ISSUE THREAD

**Issue by abhanan93** [django-import-export/django-import-export#1344]
So I know that this library provides the option to add custom or additional fields in the exported file which may not be defined the model like this:
`class A(resources.ModelResource):
    customField = Field(column_name='Custom field')`

The problem now is that these fields cannot be defined beforehand. To be more specific, I want to add whatever keys there are in the dictionary as a field to the exported file.

So far I've tried setattr in the constructor method of the above class like this:
`setattr(self, 'customField', Field(column_name='Custom field'))`

But that apparently doesn't work. Could be something that I am doing wrong but I can't figure it out. 

Thanks.

**Comment by abhanan93** [comment]
In a simple terms, how do I add fields in exported csv on the go? Per my knowledge we can add custom fields like this in the resource class: 
`custom_field = Field(column_name='Custom field')`
But what if I want to pass custom fields as a parameter to the resource class and then create them from there. I apologize if I still didn't make it clear.

**Comment by matthewhegarty** [comment]
The fields list gets dynamically created in [ModelDeclarativeMetaclass](https://github.com/django-import-export/django-import-export/blob/8ac147d5d2775cd23026b153fd978a1492088251/import_export/resources.py#L932), so the only way I can think of that you could dynamically add fields is to find a way to pass your fields into the constructor and then override the field setting logic so that it takes your supplied fields.

Sorry I can't provide a clearer answer.

**Comment by timmyomahony** [comment]
A use case for a feature like this is JSONFields. For example I have a model that has an "extra" JSON field of data. I'd like to be able to export the key/values of that JSON as columns in the export. So I need to be able to add arbitrary columns to the exported file.
