### ISSUE TITLE
Improve error information, include exact value and column

### ISSUE THREAD

**Issue by MarkoBox** [django-import-export/django-import-export#1359]
It would be nice quality of life feature if we could return more detailed error info. Including exact value/column which raised it.
Something similar to https://github.com/django-import-export/django-import-export/issues/1215

End goal would be for [row_errors](https://github.com/django-import-export/django-import-export/blob/main/import_export/results.py#L131) to be changed to namedtuple or similar formatted the same as currently but with expanded info about exact value/column where error happened. 
Caller can than more easily format this and return back in same file by appending it or new file or show in template...

As far i can see this return line [import_obj](https://github.com/django-import-export/django-import-export/blob/main/import_export/resources.py#L543) would need modification.

I would open pr for this. Any hints before i start?

**Comment by matthewhegarty** [comment]
Thanks for looking into this, it would be cool to have better error reporting, perhaps involving some kind of base class which people could override for their own formats. 

Please be aware of making any changes which could affect the existing API.  Any breaking changes would have to go into v3 which we are hoping will be released in the next 6 months or so.

If you wanted to write a short proposal and add it to this issue, I would be happy to take a look before you dive in and implement.  You might want to look at the [contribution guidelines](https://github.com/django-import-export/django-import-export/blob/main/CONTRIBUTING.md) if you haven't already.

I would also say have a look through existing PRs and issues because IIRC others may have attempted similar in the past.

 If you wanted an easy start, you could pick up #1215 as I think that would be quite an easy fix.
