### ISSUE TITLE
Integrate external data in the export

### ISSUE THREAD

**Issue by estyxx** [django-import-export/django-import-export#1388]
I would like to export a table admin, but to complete this data I have to call another service.
I was thinking to use the `dehydrate` feature to complete the data, but I can't invoke the other service for each object (would be too much expensive especially because can be there quite a lot of data...) 
So I was thinking to override `ExportMixin.get_export_queryset` or `ModelResource.get_queryset` to store the result somewhere and pick the data for each object, but resource and admin are two separate objects, I don't have my external data in `dehydrate_full_name`... 

```python
class RankSubmissionResource(ModelResource):
    # full_name = Field()

    def dehydrate_full_name(self, obj):
    	 # _PREFETCHED_USERS_BY_ID is not in this class!!! 
         return self._PREFETCHED_USERS_BY_ID[obj.id]["fullName"]

    class Meta:
        model = RankSubmission
```

```python
@admin.register(RankSubmission)
class RankSubmissionAdmin(ExportMixin, admin.ModelAdmin):
    resource_class = RankSubmissionResource

    def get_export_queryset(self, request):
        queryset = super().get_queryset(request)
        users_ids = queryset.values_list(self.user_fk, flat=True)
        self._PREFETCHED_USERS_BY_ID = ...
        return queryset
```

If override `ModelResource.get_queryset` I put the external data fetching, unfortunately, this is not called [unless the `queryset` is known](https://github.com/django-import-export/django-import-export/blob/125c1cff2958a43f9824843ee90c27f5dc0280d5/import_export/resources.py#L933). 

So I thought I can do a little workaround and override both in this way, but it's not ideal because 1. I will lose the filtering from the admin... 

```python
class RankSubmissionResource(ModelResource):
    # full_name = Field()

    def dehydrate_full_name(self, obj):
         return self._PREFETCHED_USERS_BY_ID[obj.id]["fullName"]

	def get_queryset(self):
  		queryset = super().get_queryset(request)
        users_ids = queryset.values_list(self.user_fk, flat=True)
        self._PREFETCHED_USERS_BY_ID = ...
        return queryset

    class Meta:
        model = RankSubmission
```

```python=
@admin.register(RankSubmission)
class RankSubmissionAdmin(ExportMixin, admin.ModelAdmin):
    resource_class = RankSubmissionResource

    def get_export_queryset(self, request):
       return None 
```

If you have a better approach to suggest would be very appreciated :) thanks

**Comment by matthewhegarty** [comment]
My understanding of this issue is that you would like to export a dataset, but you need additional information which is stored in a different source.  I presume you will make an API call to receive this data.

I suggest you override `before_export()` / `after_export()`.  

In `before_export()`, call the external resource and store the data locally.  You could consider writing to a local table, which might help with performance, and you could then retrieve the data by overriding `get_queryset()`.  However you could just write the data to a local variable.

In `after_export()` you will have a `Dataset` object, which you can simply iterate and [append to](https://tablib.readthedocs.io/en/stable/tutorial.html#adding-columns) to add a new column.

For example:

```python
class RankSubmissionResource(ModelResource):
    users_by_id = {}

    def before_export(queryset, *args, **kwargs):
        # call external resource here
        # you could consider writing to a local table
        # self.users_by_id = self.call_external_source()
        pass

    def after_export(self, queryset, data, *args, **kwargs):
        # update the data object with the external data
        pass

    class Meta:
        model = RankSubmission
```

This might be inefficient for large external datasets and / or if `export()` is called frequently... Perhaps caching could help here.

**Comment by estyxx** [comment]
Oh nice and easy! Thanks, I missed that approach from the documentation! 
Work also with `dehydrate_<fieldname>` thingy!
