### ISSUE TITLE
Importing Latitude and Longitude into Point Field

### ISSUE THREAD

**Issue by dgcartersa** [django-import-export/django-import-export#1401]
I'm totally stumped. CSV file contains rows with a latitude and longitude column. I'm trying to get these two columns to import into a point field on the model. My export works perfectly, but importing is an issue.

I keeps getting the error "AttributeError: 'Location' object has no attribute 'longitude'"

```
# models.py
class Location(models.Model):
    point = models.PointField(geography=True, spatial_index=True, srid=4326)
    street_number = models.CharField(max_length=30)
    street_name = models.CharField(max_length=255)

    def __str__(self):
        return "{0} {1}".format(self.street_number, self.street_name)

# resources.py
class LocationResource(resources.ModelResource):
    latitude = fields.Field(column_name="latitude", widget=widgets.DecimalWidget())
    longitude = fields.Field(column_name="longitude", widget=widgets.DecimalWidget())

    class Meta:
        model = Location
        skip_unchanged = True
        report_skipped = True
        fields = (
            "id",
            "latitude",
            "longitude",
            "street_number",
            "street_name",
        )
        exclude = ("point")
        export_order = (
            "id",
            "latitude",
            "longitude",
            "street_number",
            "street_name",
        )

    def before_save_instance(self, instance, using_transactions, dry_run):
        pprint(self.__dict__)
        pprint(instance.__dict__)
        instance.point = Point(float(instance.longitude), float(instance.latitude))
        return instance

    def dehydrate_longitude(self, location):
        try:
            geom = location.point
            if type(geom) is Point:
                return geom.y
        except:
            pass

    def dehydrate_latitude(self, location):
        try:
            geom = location.point
            if type(geom) is Point:
                return geom.x
        except:
            pass

```

**Comment by pokken-magic** [comment]
You're trying to create your Point from instance.longitude - your instance won't have a longitude. You probably want to get the longitude and latitude out of the tablib data. 

Alternatively you might be able to add Latitude and Longitude fields to your model. 

Conceptually speaking, the 'instance' is (as I recall) an instance of the model. So it can't have a longitude (unless you add that field to the model). 

A few ideas to try here (in order I think)
* create a PointWidget that pulls latitude/longitude out of the Row instance in the Clean method. Using DecimalWidget won't return a Point which is what import export really wants. 
* override import_obj and add logic for creating the Point there. 
* override 'after_import_row' on your Resource field and create the Point from the data in the row (the tablib row from which the instance is created). This might require you to make Point nullable. 

I don't think before_save_instance will work because it doesn't have access to the row to get the latitude/longitude.

**Comment by pokken-magic** [comment]
I should add that it would likely be possible to replace the whole dehydrate logic with just a point widget if you build a render Method on the widget that can serialize the point.  Then your clean method has to deserialize whatever the shape is of your serialized field into a Point. 

I would try a coordinate form (x,y) if you k that route. That should always convert to a string to fit in a csv column. If comma winds up being an issue (and it shouldn’t I think it should be quoted) use another delimiter.

**Comment by pokken-magic** [comment]
@dgcartersa did this explanation help you? Anything else I can clarify?
