### ISSUE TITLE
broken method declarations in widgets `clean()`

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1412]
**Describe the bug**

PR #479 changed the interface of the `clean()` methods in `widgets.py` to add the `row` kwarg:

```python
def clean(self, value, row=None, *args, **kwargs):
```
I believe this is broken because the kwarg 'row' appears before the arg list, therefore callers can never supply a list of args, they can only supply kwargs.

It seems like the fix could be one of two options:

1. Change 'row' to be a mandatory arg.  
2. Drop 'row' and `*args` to leave just `kwargs` (of which 'row' could be one of the kwargs).

'row' was originally added as an arg because in some cases you need to filter on more than one field to return a single row in a `ForeignKeyWidget` lookup.

Since we are changing interfaces in release 3.0, that is probably the best time to try to fix this issue without causing too much disruption to callers who have overridden `clean()`.

This issue may also be present in other areas in the code base, for example:

```python
>>> from import_export import widgets
>>> w = widgets.ForeignKeyWidget("m", field='id', 2)
                                                   ^
SyntaxError: positional argument follows keyword argument
```

**Versions (please complete the following information):**

 - Django Import Export: 2.8.0
 - Python 3.9
 - Django 4.0

**Additional context**

Original issue: #375
Also: #188, #378, #420

**Comment by matthewhegarty** [comment]
It is a tough call and I'm struggling to decide what is best.  I don't like that in most cases `clean()` gets passed the row which is never used.  It seems like a similar discussion was had when the [change was made](https://github.com/django-import-export/django-import-export/pull/420#issuecomment-193284617).  If we change this it will impact users who have implemented their own widgets.

> I am not a giant fan of that implementation of the field determining whether to send extra data based off the widget type like that. Creates some tight coupling between widgets and fields that is unattractive.

Not sure what you mean here.  Please can you clarify.  

I guess if the row is an optional kwarg, there's no harm in it being passed into `clean()`.  At least any implementations which are using 'row' wouldn't completely break.  I guess most won't be, but we don't know that.

> I wonder if it might be better to have a different field class that sends full data on the objects

Sounds interesting, but I'm not sure exactly what you mean.

**Comment by matthewhegarty** [comment]
Just thinking another option might be to preserve the existing method definition, but mark it as deprecated.  That can then call into a corrected implementation, and we can remove the original in a future release.

**Comment by pokken-magic** [comment]
Apparently I was reading the wrong version of the PR 479 commit -- in the initial version it used isinstance to determine whether to send the row data to the clean method or not. :)  Then it got updated to just always send them (parent object model to render, and parent object row to clean).  

What I was thinking was we could have whether the parent object data gets sent to those methods depend on a config parameter to Field, so it doesn't always send them superfluously, but I guess that's a fairly minor thing. 

--

In the case of this instance, I wonder if we ought to remove the arg/kwargs from default implementations of clean (on all widgets). They are only used in a realy nasty way (to allow clean to pass random args/kwargs through to get_queryset). That type of stuff feels like should only be done for a good reason, and it doesn't really add any value there except being confusing. 

ForeignKeyWidget.clean passing args/kwargs down to Widget.Clean doesn't really *do* anything (since Widget doesn't do anything with args/kwargs. 

Our design of clean/render is such that when you make a new widget and override clean, you can't just go super().clean(*args, **kwargs) you have to specify the fields required (value, or value+row). 

I could see the interface rule of clean/render being 'the thing you want to clean or render, plus args/kwargs, and figure it out' to make them very flexible at accepting the output of any customized Field as well. 

(This is a bit of a problem with some __init__ statements too, like we found in ForeignKeyWidget having kwargs before *args)

**Comment by matthewhegarty** [comment]
> I could see the interface rule of clean/render being 'the thing you want to clean or render, plus args/kwargs,

Yes, I'm thinking that the following would be cleaner and simpler, and is what Bojan was referring to in the [original discussion](https://github.com/django-import-export/django-import-export/pull/420#issuecomment-193284617):

```python
def clean(self, value, **kwargs):

def render(self, value, **kwargs):
```

I'll give it some more thought.

**Comment by matthewhegarty** [comment]
Have created a [PR](https://github.com/django-import-export/django-import-export/pull/1413) for this, having decided:

- This is broken and needs fixing.
- It makes sense to do this now because we are adding breaking changes in release 3.
- Only users who have overridden core behaviour will be affected, and the fix is minor.
- I chose to minimise the changes so have not modified `render()` 
  - I thought there is no pressing need to change `render()` at this point
- I kept `row` as a named param in `clean()`

**Comment by matthewhegarty** [comment]
Fixed in [release 3](https://pypi.org/project/django-import-export/3.0.0b0/)

**Comment by pokken-magic** [comment]
Should we close this out?
