### ISSUE TITLE
Skip row is not consistent when used inside and outside the admin

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#1437]
**Describe the bug**
Changes on the dataset are detected if using the admin to import a dataset.

Programmatic import shows no differences.

**To Reproduce**
CharField with null value in the database
`skip_unchanged = True` in the ModelResource

**Versions (please complete the following information):**
 - Django Import Export: 2.8.0 and 3.0b3
 - Python 3.8
 - Django 3.2

**Expected behavior**
Same import result in both cases.

**Additional context**

Code from 3.0b3 as an example:
```python
    def skip_row():
            ....
            else:
                # debug values for "name" column
                if field.column_name == 'name':
                    print('instance: "%s"' % field.get_value(instance), 'original: "%s"' % field.get_value(original))
                if field.get_value(instance) != field.get_value(original):
                    return False
```

Admin shows: instance "" original "None", so reports them as different
Management command shows: instance "None" original "None", no changes are reported

I think the Admin is wrong, or it could be a configuration issue :)

**Comment by matthewhegarty** [comment]
I'm getting the following when testing this, which could be another issue.  It's automatically assuming that there will be a 'categories' field in the dataset because it's auto-detected a ManyToManyField.  This is possibly not technically a bug, but it could be confusing for users.

![Screenshot from 2022-05-17 20-53-08](https://user-images.githubusercontent.com/6249838/168898586-82b0efe9-96e6-4967-a064-9c4d7f29aa6f.png)

**Comment by matthewhegarty** [comment]
It does try to import each field by default if it is not declared in the `fields` list.

**Comment by matthewhegarty** [comment]
I can reproduce your original issue now - working on a test.

**Comment by matthewhegarty** [comment]
Have got a failing test [here](https://github.com/matthewhegarty/django-import-export/tree/test-issue-1437-skip-row-not-consistent). Still some work to do.

**Comment by matthewhegarty** [comment]
This is a tricky issue caused when we have a CharField declared with `null=True` (which Django docs state should be [avoided](https://docs.djangoproject.com/en/dev/ref/models/fields/#null)).  In that case, the value of the `original` object field is 'None', whereas the empty value coming from the import is "".  I think this bug has been present in the project for a long time.

**Comment by manelclos** [comment]
The [`Field`](https://github.com/django-import-export/django-import-export/blob/main/import_export/fields.py#L25) class already has a `default` parameter to set the preferred value when an [`empty_value`](https://github.com/django-import-export/django-import-export/blob/main/import_export/fields.py#L31) is found.

The original issue is about different behaviour when importing from a management command and importing the same dataset from the admin. Notice that the dataset is generated from a custom form reading from a database. So I got those None directly from de database.

The question is why the same dataset is interpreted in different ways, what causes the None to be converted to empty string when using the same form/dataset/resource from the admin.

**Comment by matthewhegarty** [comment]
Hi Manel.  I might have misunderstood the issue, so please feel free to correct me.  Are you able to reproduce it using the example app?  I think I have been able to reproduce the same issue (or something like it).

If you check out my [PR](https://github.com/django-import-export/django-import-export/pull/1438), you should be able to reproduce the issue.  It involves having a field which is set to default null.  

To reproduce,

1.  Check out my PR
2.  Run the migrations and start the server
3.  Create a book instance (notice the 'isbn' field will default to null)
4.  Import the books.csv file listed in the PR.  Since the 'isbn' value is empty ("") it will not match the 'None' value and you will get an update not a skip.

To reproduce the issue, you will have to comment out the fix I have added to `skip_row()`.

> The [Field](https://github.com/django-import-export/django-import-export/blob/main/import_export/fields.py#L25) class already has a default parameter to set the preferred value when an [empty_value](https://github.com/django-import-export/django-import-export/blob/main/import_export/fields.py#L31) is found.

Yes, but this only happens if the user defines a 'default' param when they declare the field - it doesn't happen automatically.

**Comment by manelclos** [comment]
Hi @matthewhegarty, just tried your PR and it works as you say. When all fields other than `isbn` are equal, you get an update, and with your code it changes to skipped.

Still, I don't think this is the way to go because it changes default behaviour, and you can already change this default behaviour using the `default` attribute. I don't want to start a single quote vs double quote 😄.

About the fix for ManyToMany on the PR, I fully agree.

Let me try to add a test so we can be on the same page about the problem I'm facing with the nullable CharField.

**Comment by matthewhegarty** [comment]
OK no problem.  I'll be interested to see more detail about your issue, because I guess adding `default` to `Field()` doesn't solve it?

**Comment by manelclos** [comment]
Hi @matthewhegarty, I've setup the failing scenario in the admin import test, but I'm unable to reproduce, I always get None on "isbn" field both for `instance` and `original`. I will try to debug on the server, and also try the `default` setting.

**Comment by matthewhegarty** [comment]
Hi Manel - I wonder where we go to with this issue... Do you want to have another look?

**Comment by manelclos** [comment]
@matthewhegarty yes, still on my todo list. Will invest some time in release 3 soon, as when updating from 3.0.0b2 to 3.0.2 some functionality is lost for us (probably in the Changelog, but haven't checked ;) )

**Comment by matthewhegarty** [comment]
Hi Manel - we're aiming for release-4 in the near future (now at rc0).  Just wondering if there is any desire to pick this up?  If not I will close for now.
