### ISSUE TITLE
FileNotFoundError on Import

### ISSUE THREAD

**Issue by Yodale1000** [django-import-export/django-import-export#1454]
When i try to upload a xlsx file i get this error:
https://sentry.io/share/issue/b669a7f8cb974080a04b78e3e1882b90/

**Comment by matthewhegarty** [comment]
- Are you using [release 3.0 beta](https://pypi.org/project/django-import-export/3.0.0b4/)?
- Are you running in a multi container environment, or any setup where the file may not be present on the local FS, if so please read [these docs](https://github.com/django-import-export/django-import-export/blob/release-3-x/docs/getting_started.rst#import-confirmation) on temp fs storage?

If this doesn't explain it, please can you provide more information so that we can try to understand what is going on?
