### ISSUE TITLE
EOF page showing up when I try to upload excel file

### ISSUE THREAD

**Issue by ade555** [django-import-export/django-import-export#1524]
I am currently trying to upload an excel file with about 800k rows to my admin panel, but I keep getting a blank page that displays "EOF". When I upload a smaller amount of data (<100 rows), I don't get this issue. Is there something I can do to make this work?

**Comment by matthewhegarty** [comment]
Sounds like it is timing out due to the volume of data.  If you look at the network tab in your browser Dev Tools window it should confirm this.  You could try to enable [bulk mode](https://django-import-export.readthedocs.io/en/latest/bulk_import.html) to speed it up, but large file uploads in the browser aren't really suitable.  The solution would be to upload using a celery job or similar.  Please refer to the [docs](https://django-import-export.readthedocs.io/en/latest/celery.html).

**Comment by ade555** [comment]
Alright. Thank you.
