### ISSUE TITLE
Error importing not existing model into database with many to many field with blank and null as True

### ISSUE THREAD

**Issue by manuel-talavera-mck** [django-import-export/django-import-export#1558]
**Describe the bug**
Error when you are trying to import new instance of a model (not existing previously). The model must have a many to many  field with attributes blank and null with True value.

I get the following error:
```
Traceback: Traceback (most recent call last):
  File "i/venv/lib/python3.9/site-packages/import_export/resources.py", line 744, in import_row
    if self.skip_row(instance, original, row, import_validation_errors):
  File /venv/lib/python3.9/site-packages/import_export/resources.py", line 630, in skip_row
    original_values = list(field.get_value(original).all())
AttributeError: 'NoneType' object has no attribute 'all'
```
**To Reproduce**
1. Have a model with a many to many to other model. The field must have attributes null and blank as True
2. The Resource class must have as first configured field the many to many field
```python
class MyModelResource(resources.ModelResource):
    many_to_many_key_field = fields.Field(
        column_name='many_to_many_key_field',
        attribute='many_to_many_key_field',
        widget=ManyToManyWidget(ManyToManyOtherModel, 'id'),
    )
```
3. Try to import excel file with a row. The row must have the many to many field as null/blank
4. See error: AttributeError defined above: 

'NoneType' object has no attribute 'all'

**Versions (please complete the following information):**
 - Django Import Export: 3.1.0
 - Python 3.9
 - Django 4.1.7

**Expected behavior**
The instance of model is inserted into database.

In a many to many relation must exists previously the related object in Django, in other cause an error is gotten.

I'm not sure, but I guess that maybe when an object is defined as "new", it must not be checked as skippable row. I mean, if is new, always must be inserted into database.

In this line: https://github.com/django-import-export/django-import-export/blob/main/import_export/resources.py#L724, you know that is a new object. 

But, in this line you are checking if the row must be skpped: https://github.com/django-import-export/django-import-export/blob/main/import_export/resources.py#L744

I guess I'm ignoring other cases I don't know about, sorry in that case.

EDIT: Sorry, I have edit because i meant to say many to many insted of ForeignKey.

**Comment by matthewhegarty** [comment]
Thanks for raising.

The check on line 725 only happens if the row has been marked for delete.  If it has, and it is new, then it is assigned status of 'SKIPPED'.

The check on line 744 is necessary because users can implement their own skip logic.

As for the error, I couldn't reproduce with the example app, because the 'original' instance always returns a `ManyRelatedManager` for the m2m (categories) field, and this never returns `None` when `all()` is called.

Is there something I'm missing?  Maybe your migrations haven't been run?

Is it possible you can reproduce this issue using the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?

I've tried to reproduce with the attached test case, which you can copy into test_resources.py

[test.txt](https://github.com/django-import-export/django-import-export/files/10913449/test.txt)

**Comment by carlosal0ns0** [comment]
The error occur when importing a new instance (pk = None).  This happens because Django returns None when trying to retrieve a related manager for a model with a None primary key.

Here is a test case for example app:

`class ManyToManyWidgetDiffTest(TestCase):
    fixtures = ["category", "book"]

    def setUp(self):
        pass

    def test_m2m_on_new_entity(self):
        # issue 1558
        class _BookM2MResource(resources.ModelResource):
            categories = fields.Field(
                attribute='categories',
                m2m_add=True,
                widget=widgets.ManyToManyWidget(Category, field='name',
                                                separator='|')
            )

            class Meta:
                model = Book

        dataset_headers: list[str] = ["id", "categories"]
        dataset_row = [None, None]
        dataset = tablib.Dataset(headers=dataset_headers)
        dataset.append(dataset_row)

        book_resource = _BookM2MResource()
        book_resource._meta.skip_unchanged = True

        result = book_resource.import_data(dataset, dry_run=False)

        self.assertFalse(result.has_errors())
        self.assertEqual(len(result.rows), 1)`
        
        
        
i also created a PR with a simple solution 
https://github.com/django-import-export/django-import-export/pull/1560

**Comment by matthewhegarty** [comment]
To reproduce in test application change the `BookResource` declaration in `admin.py` to:

```python
class BookResource(ModelResource):

    class Meta:
        model = Book
        skip_unchanged = True
```

Then import the attached file via the Book import in the Admin interface.

[books copy.xlsx](https://github.com/django-import-export/django-import-export/files/10934923/books.copy.xlsx)
