### ISSUE TITLE
Maybe CharWidget.clean() should always return a string?

### ISSUE THREAD

**Issue by nuarhu** [django-import-export/django-import-export#1573]
Hi there,

it just took me a while to get to the root of an error with my excel import, and I wanted to raise this here as a question. At least it might spare someone else effort.

Use Case: Excel Import with cells that contain numbers that are imported into Django's CharField (or TextField)
Django Version: 4.2
django-import-export version: 3.2.0

So in my case, one of the columns contains postal/zip codes that are stored in a Django CharField.
Note that I also explicitely told Excel to use "Text" as format for all columns but, well, it had no effect at all.

The resource field was at first defined using django-import-export's CharWidget:

```python
    postal_code = Field(attribute='postal_code', column_name='PLZ', widget=CharWidget())
```

The actual import would work but I have custom code that hooks into `after_save_instance` and `after_import` to do an update on a search index and it relies on the types as defined in the Django model (which is `str` in this case).
With the CharWidget in place, this code would break because `instance.postal_code` would have the type `int` instead of the expected `str`.

I've overridden the CharWidget like this:

```python
class RealCharWidget(Widget):
    def clean(self, value, row=None, **kwargs):
        # make sure it's a string
        return str(value)
```

and updated the resource field to use it:

```python
    postal_code = Field(attribute='postal_code', column_name='PLZ', widget=RealCharWidget())
```

and my custom code now also works fine. It took me a while to even think of looking into CharWidget because I really did expect it to make sure that the value returned during import is a string.

**Comment by matthewhegarty** [comment]
Hi, thanks for raising.

I think I agree that this is a valid bug.  The [definition](https://github.com/django-import-export/django-import-export/blob/8c9a5ef87a5c8ca47f821dec434a27b99468dcf4/import_export/widgets.py#L34) of `clean()` is:

> Returns an appropriate Python object for an imported value.
> 
> For example, if you import a value from a spreadsheet,
> `clean()` handles conversion of this value into the corresponding Python object.

It doesn't really make sense for `CharWidget` to return anything other than a string from `clean()`.  I note that this has been the behaviour of `CharWidget.clean()` since it was created, and it has always inherited from `Widget.clean()`.

My guess is that this may only happen for spreadsheets which have int values in columns (as per your example).  I would have to test.  I'm surprised it hasn't come up more often.

We wouldn't be able to change this without first making it optional to return str values, so there'd have to be an kwarg to opt in.  In a future release we would make returning a string the default behaviour.

**Comment by pokken-magic** [comment]
fwiw, i've had similar issues with Pandas with phone #'s and Zipcodes not behaving right unless you're explicit about the format. 

The place where this can gets more complex than it looks is if you have nullable fields; if you start str()'ing Nones you may have issues.  IIRC, a None will str out as "None" - so worth double checking that.
