### ISSUE TITLE
Importing Related Model Using Same Sheet

### ISSUE THREAD

**Issue by yassinsameh** [django-import-export/django-import-export#1591]
How can one import two Models using the same excel sheet: 

Simplified example:
```
class Person:
        name = models.CharField(max_length=128)
class SocialMedia:
        user = models.OneToOneField(User, on_delete=models.CASCADE)
        facebook_url = models.URLField(null=True, blank=True)
        twitter_url = models.URLField(null=True, blank=True)

```
Sheet contains the columns: name, facebook_url, twitter_url

How can the Person be created, and then the SocialMedia will use that Persons pk to create a new object. 

Been through many tickets, docs and trial but can't seem to find a robust way to do this that ensures:
1) Displaying correctly in preview
2) Validates both models before preview and only commits after submit

Open to all suggestions

**Cases this is important:**
- When there are no unique attributes for the Object being referenced

**Comment by matthewhegarty** [comment]
I don't have time to post a more detailed response.

Take a look at using some of the import hooks.  You can [create a related object before the row is persisted](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#creating-non-existent-relations).  If necessary you can store the reference to that object as an attribute on the created instance, so that it can be read later.

It might need some manipulation to display in preview, best thing is to step through with debugger and look at what is available.

All commits are rolled back after preview so it would only be persisted on submit (point 2).

This kind of thing has come up before so I suggest search Stack Overflow to see related answers (if not already).

**Comment by yassinsameh** [comment]
Thanks for your efforts on this package and for clarifying @matthewhegarty , the fact that everything will be rolled back automatically helped.
I used Model.objects.update_or_create to keep updating the same instance as i provide a unique identifier.
