### ISSUE TITLE
Strange issue importing XLSX from LibreOffice

### ISSUE THREAD

**Issue by SchrodingersGat** [django-import-export/django-import-export#1642]
Hi,

Over on the [InvenTree project](https://github.com/inventree/InvenTree) we have encountered a [strange issue](https://github.com/inventree/InvenTree/issues/5526) where importing a `.xslx` file (which has been generated using LibreOffice) will cause the server to be stuck forever (until a web timeout occurs, or the server is restarted).

As noted in the other thread:

- If the same data is uploaded in a different format (e.g. `csv`) the problem does not occur
- If the same file is re-saved using microsoft excel (no change to the data) the problem also does not occur

The other thread has a sample file which demonstrates the problem, although most likely would require an InvenTree server instance to reproduce.

At this stage, looking for any pointers as to where I might look. The database logs indicate that there are a *lot* (thousands) of database hits going on.

We are running `v2.5.0` of `django-import-export` - however I have also tested with latest version and the same issue is present.

In terms of any custom code we are running, the data is imported through a custom `PartManager` class:

https://github.com/inventree/InvenTree/blob/200bc5bd3d56ca2c1cd1a7cedab63e4cce0f5b5f/InvenTree/part/admin.py#L16

this is itself a subclass of the `InvenTreeResource` class:

https://github.com/inventree/InvenTree/blob/200bc5bd3d56ca2c1cd1a7cedab63e4cce0f5b5f/InvenTree/InvenTree/admin.py#L11

Any hints or suggestions here would be greatly appreciated. It's a weird one.

**Comment by matthewhegarty** [comment]
Hi Oliver

Never heard of InvenTree, looks like an interesting project.

In terms of things you can try...

- Have a good look at the file (if not already)
  -  Does it contain hidden rows or columns, worksheets etc

- Download and install [tablib](https://tablib.readthedocs.io/en/stable/tutorial.html#importing-data).  Follow instructions for importing data and try loading one of the problem files.
  - If this works without issue (i.e. you get a dataset loaded into memory), then you can probably rule out any parsing issues with tablib or any of its dependencies
  - import-export uses tablib as the core module for parsing data into memory.
  - If you see issues in import_export with one file format and not others (i.e. xlsx vs csv) then this would be puzzling because in both cases import_export is iterating over a tablib dataset. 
  - Also checkout the issues in tablib and openpyxl just in case something already exists

With there being a lot of db hits, I would be interested in seeing where these are coming from, and what is taking the time.  Are these large files you are importing?  Can you profile at all and see what is taking the time?

I had a quick look at the thread and noticed you repeatedly see `LIMIT 21` in your queries.  This looks unusual, is there some pagination or overridden query behind this?  Do you need to review your `select_related()` / `prefetch_related()` calls?

I would also recommend upgrade to the latest version of import_export as soon as you can, because v2 now unsupported and v4 is on its way.

**Comment by matthewhegarty** [comment]
Closing because I don't think this is a import_export issue.  Feel free to comment if you do find a bug.

**Comment by SchrodingersGat** [comment]
@matthewhegarty I have not yet worked out exactly what is going on, but I have found one interesting thing.

Importing the "fault" file with tablib, the import process takes ~5 seconds (for a 2-row file):

```python
import tablib

FN = "toimport.xlsx"

with open(FN, 'rb') as fh:
    data = tablib.Dataset().load(fh)

print(data.headers)
```

If I open the same file in excel, and re-save as a *new* file, then the new file (saved with excel) loads in 0.5 seconds. I'm not sure what this means exactly, but there is a marked difference in terms of time taken to import the data

**Comment by matthewhegarty** [comment]
Thanks for the update.

- I presume that you lose the 1m rows when you resave? (the size on disk changes?)
- Is the 5 sec load time repeatable if you load the exact same file twice?

**Comment by SchrodingersGat** [comment]
> * I presume that you lose the 1m rows when you resave? (the size on disk changes?)

The 1m rows is reduced to a single row (which reflects "reality") but the file size actually increases:

![image](https://github.com/django-import-export/django-import-export/assets/10080325/e56f01ab-f82a-4ffe-b7e1-7d25907656ef)


> * Is the 5 sec load time repeatable if you load the exact same file twice?

```python
import tablib
import time

dataset = "toimport.xlsx"

for i in range(5):
    t1 = time.time()


    with open(dataset, 'rb') as f:
        data = tablib.Dataset().load(f)

    t2 = time.time()
    dt = t2 - t1

    print(f"Test {i} took {dt:.3f} seconds - loaded {len(data)} rows")
```

Output:

```
Test 0 took 4.726 seconds - loaded 1048575 rows
Test 1 took 4.374 seconds - loaded 1048575 rows
Test 2 took 4.531 seconds - loaded 1048575 rows
Test 3 took 4.799 seconds - loaded 1048575 rows
Test 4 took 4.504 seconds - loaded 1048575 rows
```
