### ISSUE TITLE
`diff_match_patch` replacement

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1694]
**Describe the bug**
[`diff_match_patch`](https://github.com/google/diff-match-patch/issues/143) seems unmaintained.  it looks like there is a [maintained fork](https://github.com/dmsnell/diff-match-patch/tree/issues/69-broken-surrogate-pairs).

This library is used to show the differences between persisted and imported values.  It is presented in the UI and also retained in each row.

**Comment by andrewgy8** [comment]
@matthewhegarty Ill take this one on and solve it. 

As you say, the Google repo is now in read-only mode and there is a fork which is maintained for all the clients. I dont see any major changes to the API that can affect us right now in the new fork. 
As far as I can tell though, there are no releases being done of the python3 client. Which means that we will need to pull it directly from the repo if we want to use this fork.

Shall we use the repo directly as the installation method?

There are other options I see:
1. Fork the project and maintain it ourselves. I dont see this being a major issue since the code is quite stable. We can strip the code base down as well to make it easier on ourselves. 
2. Include the relevant parts of the project in Django Import Export's code base. Itll be an additional ~300 lines from my rough estimation (+ tests). 

Im open to any other ideas?

**Comment by matthewhegarty** [comment]
Thanks Andrew!

> Shall we use the repo directly as the installation method?

I think we can do this, but I expect we'd have to pin to a specific commit in our `requirements.txt`.  They aren't creating versioned releases and everything goes onto master, so my worry would be that if we built the same version of import_export at different times, the code coming from `diff_match_patch` fork could be different 🤷‍♂️ 

I think I would prefer that to the other two options.  It would be ideal to reference this issue so we know in future why we use the repo directly.

**Comment by andrewgy8** [comment]
Yep, totally agree with that. I'll go ahead and pin it to the latest commit on master.

**Comment by andrewgy8** [comment]
A bit of a hiccup, and still trying to figure out a clean way of making this work... there is no setup.py in the python3 directory of the project. Is there some trick Im missing to install this package without a setup.py file? I was under the impression that was a mandatory file. 

Otherwise, Ill have to submit a PR for this in repo.

**Comment by matthewhegarty** [comment]
Ah - we should probably be using [this version](https://pypi.org/project/diff-match-patch/#history) and that would be ok (?)
