### ISSUE TITLE
Using a ManyToManyWidget does not allow to ignore an empty value

### ISSUE THREAD

**Issue by nemesifier** [django-import-export/django-import-export#1788]
**Describe the bug**

```python
    def clean(self, value, row=None, **kwargs):
        if not value:
            return self.model.objects.none()
```

Try this in the python shell:

```python
>>> self.model.objects.none() == self.model.objects.none()
False
```

This means that even modifying a field to add `Model.objects.none()` to the empty values doesn't work to ignore the empty queryset, so the cleaned value is always saved.

This can cause issues when the model being imported is referenced by an optional OneToOne relationship from another model and this model has an optional m2m, in this case the m2m is saved even when it shouldn't and it raises an error. 

**To Reproduce**
...

**Versions (please complete the following information):**
 - Django Import Export: 3.30
 - Python 3.8.10
 - Django 4.2

**Expected behavior**

I think we could return an empty list instead of an empty queryset in this case, that way we can add '[]' to `empty_values` in `Field` to solve it. Alternatively we could just return an empty string and modify the rest of the code to ignore falsy or empty values.

**Screenshots**

![Screenshot from 2024-04-11 11-22-07](https://github.com/django-import-export/django-import-export/assets/841044/50b7b3f8-25c8-4bb7-a23f-b73cef33967b)

**Comment by matthewhegarty** [comment]
Thanks for raising.  I would suggest to look at [release 4](https://django-import-export.readthedocs.io/en/4.0.0-rc.2/release_notes.html).  We will be changing the interface in a few places to standardize it, so would be a good opportunity to put a fix in.  I think that returning an empty list would work ok, so no need to modify `Field`.

  If you felt like creating a PR, that would be appreciated.  Contributing guidelines are [here](https://django-import-export.readthedocs.io/en/4.0.0-rc.2/contributing.html#guidelines-for-reporting-an-issue-feature).

**Comment by matthewhegarty** [comment]
I looked into this and it is not a simple issue.  I think your issue is that you want to prevent the `RelatedManager` methods from being called [here](https://github.com/django-import-export/django-import-export/blob/0de0fdc8419d2046d3d5072f2d8549b4d1050a46/import_export/fields.py#L138).  You could do this with a subclass of `ManyToManyWidget` which returned `None` from `clean()` and then create a Field with `saves_null_values=False`.  This prevents the `RelatedManager` methods from being called, but may break in cases where an empty queryset or list should be processed, for example when clearing an m2m field.

I'm open to suggestions but I don't see how we can safely add this fix to the core library.  Test code in #1980.

**Comment by nemesifier** [comment]
@matthewhegarty thanks for the info :pray:
