### ISSUE TITLE
Customize export format depending on file type

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1844]
In v4, we standardised the widget `render()` method to return strings.  This is because the v3 implementation had a mixture of formats, and this inconsistency caused issues for users.

We added the [`coerce_to_string`](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#modify-render-return-type) param to address this.

However it means that when users export to xlsx, they now get strings instead of native values (unless they set `coerce_to_string`).  This may cause problems when exporting to different formats such as xlsx and csv.

A future enhancement would be to dynamically detect the file type (probably xlsx or otherwise) and dynamically set the `coerce_to_string` param accordingly.  This would mean that native types such as dates and numeric values would be exported correctly.

**Comment by AyushDharDubey** [comment]
I would like to open a PR to address this issue. I propose the following solution:

- In `admin.py` and `mixins.py`, we will pass a new parameter `coerce_to_string` to the function call `get_data_for_export()`. This parameter will be set to `True` if `type(file_format)` is none of [`XLSX`, `XLS`, `ODS`], otherwise it will be set to `False`.
- This parameter will be passed through `kwargs` all the way down to `fields.Field.export()`, where we will update `self.widget.coerce_to_string`.

**Comment by matthewhegarty** [comment]
Thanks - this would be a great addition to the forthcoming 4.2 release.  Leave it with me to have a think about your proposal and I'll let you know.

**Comment by matthewhegarty** [comment]
I looked into it and I think that your approach will work.  Users might have set a `coerce_to_string` value themselves on a custom widget, so somehow we'd have to make sure it didn't override that, which I think will be tricky.  This could potentially break existing implementations.

However because we are fixing so that this matches v3 behaviour, I think it is ok (I will document it in the release notes as well).

So happy for you to proceed with this.

**Comment by AyushDharDubey** [comment]
I'm sorry for the delay in addressing this issue. I thought I had informed that I would be unavailable, but it seems I forgot to do so. I’ve been busy with some unavoidable work for the past two weeks, and I won’t be able to resume work on this for another 3-4 days. If someone else is willing to take up the issue in the meantime, please feel free to assign it to them.  I won't mind. Otherwise, I will continue my work after a few days.

**Comment by matthewhegarty** [comment]
Hi, no problem at all, happy for you to pick this up when you can. Thanks for contributing!
