### ISSUE TITLE
Looking for help to maintain django-import-export

### ISSUE THREAD

**Issue by bmihelac** [django-import-export/django-import-export#271]
I'm looking for somebody that can help in handling pull requests and addressing issues.

Note:  I'm not leaving, just currently do not have much time as I would like to devote.

Any candidate?
I'd like to directly call @rhunwicks and @manelclos as top contributors in recent time.

**Comment by manelclos** [comment]
Hi @bmihelac, I'd love to help. I'm actively using the project and have some ideas on mind. I can handle simple pull requests and review bigger ones for team approval.

**Comment by bmihelac** [comment]
Great, thanks @manelclos

**Comment by manelclos** [comment]
I'd like to start by closing old issues that had been either solved or answered, politely asking for a reopen if needed.

Also, as the import-export application is used in many scenarios, it would be great if you can define your vision about what should go into impor-export and what should be provided as a plugin or as examples in the documentation, some thoughts about that:
- Extra functionality as in https://github.com/django-import-export/django-import-export/issues/258, I'd say that import-export should make this easier to implement, either by improving documentation or code, and maybe at some point the feature can make into core import-export
- Geo formats: as a plugin, agreed
- https://github.com/django-import-export/django-import-export/issues/189 I think should be solved by documentation examples, rather than creating a class for every use case

**Comment by bmihelac** [comment]
@manelclos that looks great; I agree with all your points for tickets. 

As for vision I would like django-import-export to:

* be as small as possible without features that bring lots of code into the library
* be customizable and extendable (it is often case where specific formats should be imported or exported)
* be stable and well tested

**Comment by manelclos** [comment]
@bmihelac great! let's work on those :)

**Comment by rhunwicks** [comment]
I'm not in a position to take on a formal role. But I'm very happy to try
and contribute where I can. In particular, I'm happy to review PRs and
comment on them.

**Comment by rhunwicks** [comment]
I think that's a great vision.

**Comment by bmihelac** [comment]
thanks @rhunwicks

**Comment by andybak** [comment]
Considering you have a Github organisation named after the project - how about encouraging people who want to extend the core to make use of that?

If @JohnSmith has an idea for an django-import-export-foo extension then you can create a repo under your own umbrella and add him as a committer (without needing to make him a committer for the core project).

This way the core stays small but there's still a semi-officially blessed 'contrib' list that people can easily find and contribute to.
