### ISSUE TITLE
How to apply it on the frontend side?

### ISSUE THREAD

**Issue by maltitco** [django-import-export/django-import-export#278]
I have a new problem (on frontend).
Data are loaded but after approval refreshes the page and I have information: "This field is required" over the File field.

link to code: http://wklej.org/hash/30ac274b704/

![zrzut ekranu 2015-05-27 o 15 15 52](https://cloud.githubusercontent.com/assets/1561204/7853961/ecc3cade-0514-11e5-8254-9ae0072ad3b6.png)
![zrzut ekranu 2015-05-27 o 15 16 10](https://cloud.githubusercontent.com/assets/1561204/7853962/ecc4b62e-0514-11e5-8caf-8b5166091114.png)

**Comment by manelclos** [comment]
Hi @maltitco are you testing this locally or hosted somewhere?

**Comment by maltitco** [comment]
@manelclos I testing this locally

**Comment by manelclos** [comment]
@maltitco I'd say that you are creating a different temporary file everytime instead of reusing the uploaded one:

            with tempfile.NamedTemporaryFile(delete=False) as uploaded_file:

It looks that you are trying to do a lot of work already done in the admin, maybe this is helpful:
https://django-import-export.readthedocs.org/en/latest/getting_started.html#admin-integration

**Comment by manelclos** [comment]
Hi @maltitco, any news on this issue?
