### ISSUE TITLE
Feature request - email you an exported result rather than returning in band

### ISSUE THREAD

**Issue by gone** [django-import-export/django-import-export#386]
My use case is pushing the export into a celery job and then emailing the result. I'd be happy to take a try at it if there's interest.

**Comment by bmihelac** [comment]
Hi @gone,
I think that such extension should go in another package to make django-import-export as small as possible. 

Would be glad to link in documentation if you make such extension.

**Comment by gone** [comment]
Sounds good, I'll look into doing that

**Comment by staranjeet** [comment]
Apart from the export process, what if this feature is available for import also. This will be useful when we are importing a csv which contains many rows(lets say > 50K or more). Instead of making the user wait to see if the csv upload is complete, display a message to the user that csv is being uploaded and if any errors pop in, then they are mailed to the user.

@bmihelac : Any pointer if I want to do this using celery, How can i start.
@gone: Are you writing that package?

**Comment by rhunwicks** [comment]
One thing that I think we could do is change the way the results are stored. At the moment we calculate the diff as part of the import and save it in the `row_result`. In my case, with many foreign keys, calculating the diff is expensive. It also results in the html embedded in the diff.

For an emailed result, I guess that we would control over the formatting at the output stage. I.e. some people might the full results as html, others might want a summary, and others still might want a CSV of the results.

If we change the `import_data` so that it stores the old and new instances in the `row_result` and then change `diff` to a property so that it returns the current formatting, but calculated at the time it is asked for, then we defer processing (which might never be called - I do batch imports and never show the diff) and provide flexibility for other people to do custom reporting. I don't know whether we need to worry about the memory implications of keeping two copies of each object around until the import finishes. If we decide to go ahead, I would be happy to make those changes as part of #346

**Comment by koedal** [comment]
> Apart from the export process, what if this feature is available for import also. This will be useful when we are importing a csv which contains many rows(lets say > 50K or more). Instead of making the user wait to see if the csv upload is complete, display a message to the user that csv is being uploaded and if any errors pop in, then they are mailed to the user.
> 
> @bmihelac : Any pointer if I want to do this using celery, How can i start.
> @gone: Are you writing that package?

I have this same need now as my import can take 30+ minutes. I would like to do the import as a Celery task and email the results and allow the user to select Confirm from the email and finish the import in a Celery task.

@bmihelac Any tips on making this work?

**Comment by yozlet** [comment]
This is something that would be useful for me too. However, I'd like to keep most (maybe all) of the interaction in the web app, and I'm using [django-rq](https://github.com/rq/django-rq) rather than Celery. Either way, here's how I'm thinking of doing it:

* The bulk of the work, including the diff HTML generation, happens in [`Resource.import_data()`](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L539). This is a good unit to run in its own task. We need to wrap it in a couple of extra things to manage progress reporting - see below.
* It spits back a giant [`Result`](https://github.com/django-import-export/django-import-export/blob/master/import_export/results.py#L74) object: despite its size, it _should_ (fingers crossed) be relatively easy for Celery/rq to [serialize](http://docs.celeryproject.org/en/latest/userguide/calling.html#serializers) as a task result.
* If you're happy with the email-based workflow, the task should have a [callback](http://docs.celeryproject.org/en/latest/userguide/calling.html#linking-callbacks-errbacks) which templates the `Result` into an email and sends it. However, you'll still need another view which shows those results in a confirmation page so that the confirmed (non-dry-run) import can happen. In the existing synchronous flow, [`Admin.import_action()`](https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L236) does the work of combining [`ConfirmImportForm`](https://github.com/django-import-export/django-import-export/blob/master/import_export/forms.py#L30) with the received `Result`. The good news is that we can still keep the vast majority of the existing logic there, but the `Result` has to come from the Celery result backend (probably [`django-celery-results`](https://django-celery-results.readthedocs.io/en/latest/), which can use either the DB or an existing cache to store/retrieve it).
* I want everything to happen through the web, so ideally I'd like submission of the import form to redirect to a progress page while the import is being processed. [buildwithdjango.com has a really good explanation of how it would work](https://buildwithdjango.com/blog/post/celery-progress-bars/) - despite that page being quite long, the concepts aren't too horrible and the code required is pretty small. To make it useful for django-import-export, the main question is: how do you make the import update its task state? Fortunately, this should be relatively easy:
    1. Our `ModelResource` subclass needs some extra instance variables. Define these in the `__init__()`, but leave them all blank:
		1. `import_task`: stores a handle to the running Celery Task
		1. `import_rows_progress`: stores how many rows have been processed so far
		1. `import_rows_total`: stores the total number of rows to be processed 
	1. However we wrap `Resource.import_data()` into a Task, we need to set those three variables when the Task is started. `import_rows_total` will just be `dataset.height`.
    1. `Resource` includes [a load of useful hooks](https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.resources.Resource) which can be overriden for custom behaviour. We can override [`after_import_row()`](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L456) to increment `self.import_rows_progress` and then execute `import_task.update_state()` (see "Getting Progress Back To The Client" in [that buildwithdjango.com explainer](https://buildwithdjango.com/blog/post/celery-progress-bars/)). However, we _don't_ want to update it for every single row, as it'll add far too much friction to the import process. Instead, we need to pick an interval for the updates - say, every 20 rows - and then call `update_state()` every time `self.import_rows_progress % UPDATE_INTERVAL == 0`
	1. The progress page itself is pretty simple. Off the top of my head, it needs:
		1. The JS to continually poll for progress updates, and display progress
		1. Another couple of lines of JS to recognise when the task is complete, and redirect to the results-display view I mentioned above. (Note: to check task completeness, you need to check Task **state**, and not rely on `import_rows_progress == import_rows_total`, since there's some finish-up work after that.)
		1. The `get_progress` route & view that the JS calls

... and I think that's about it. Lots of little things in different places rather than a single huge modification; the difficulty is in knowing where those things need to go, and then being able to test it properly.

**Comment by yozlet** [comment]
Oh, almost forgot an important detail:

You're using Celery, I'm using rq. Despite these differences, the two frameworks are similar enough that it _should_ be easy to abstract the specifics out so that 95% of the code doesn't care.

**Comment by joost** [comment]
Anyone that did some work on this? Would really appreciate it!
I have imports of 20k lines (CSV) that are not possible without some background processing (it simply takes too long).

**Comment by yozlet** [comment]
I've done a couple of minor bits that are very specific to my employer's needs, nothing that's generalisable yet, and unfortunately my schedule is packed enough that I can't devote continual time to get this done.

**However, if there's anyone else here who's interested in doing this work, I will happily be an on-hand advisor/reviewer while you're working through it.** Don't worry about doing a polished/complete solution, just the bones of the needed structure would be a great start.

The ideal candidate for taking this on should have these qualities:

1. They know they'll depend on Django Import/Export for at least the next six-to-twelve months, and so they have an interest in understanding it better. D-IE's code is pretty readable; like every other significantly large code base it could be better, but the code is still small and clear enough to be relatively understandable. (As anyone who's spent enough time with it knows, the documentation is a good starting point but has some major gaps. I stuck with D-IE because I've always been able to work through the code when the documentation failed.)

2. They want to improve their skills in Python, Django and distributed systems. They **don't** have to be a great programmer for this - there'll be enough reviewers to give them guidance. They **do** have to want to learn how to write complex code with test coverage while keeping it readable.

3. They have enough Python/Django skills to read [my proposal above](https://github.com/django-import-export/django-import-export/issues/386#issuecomment-455361671) and understand at least 50% of what I'm talking about. Doesn't have to be everything, and there's also a good chance I've made some major mistakes. A willingness to explore, learn and try things is more important.

4. They would directly benefit from this feature.

**Comment by joost** [comment]
@yozlet thx. I started importing directly into the db with csv's :)

**Comment by timthelion** [comment]
This functionality is now implemented in the library [django-import-export-celery](https://github.com/auto-mat/django-import-export-celery)
