### ISSUE TITLE
"Imported file is not in unicode"

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#390]
django-import-export `0.4.2`
Django `1.8.8`
tablib `0.10.0`
Python `3.4.3`

I'm getting this error on trying to import a file from admin interface, exclusively on production server, cannot reproduce it on my development machine:

> Imported file is not in unicode: 'ascii' codec can't decode byte 0xd0 in position 120: ordinal not in range(128)

The file is in UTF-8 even after uploading, I checked it in the tmp dir:

> UTF-8 Unicode text, with very long lines, with CRLF line terminators

I haven't found a way to see a traceback yet, because I cannot enable debugging in production and also the error is not raised properly (HTTP status 200 returned) so it's not sent to me by email. Continuing to investigate it now, will appreciate any suggestions.

Related: #347 #72

**Comment by int-ua** [comment]
CLI import with https://gist.github.com/bmihelac/434fceb6ba8e752f08d3 works fine.

**Comment by bmihelac** [comment]
Does CLI import works in production? 
Can you `./manage.py runserver 0.0.0.0:8000` just to exclude proxy?

**Comment by int-ua** [comment]
Yes, CLI import works in production.
I was not able to reproduce it in my development environment. IIRC, I even tried to setup a local server on a different machine and wasn't able to reproduce it. The production server is behind Cloudflare, that could be the reason.
Also, I think I remember reproducing it in the dev environment after that, but being too busy to dig it or even writing here, just used CLI.
I'll try again later, just have to look up what Resource I've written a month ago.

**Comment by int-ua** [comment]
No, looks like it was a false memory.

BTW, is it my mistake too or there are no `develop` branch and it's mentioned in the root readme?

**Comment by int-ua** [comment]
I haven't noticed this problem for a long time now, maybe because I'm using exclusively CLI import on production. I'll close this for now.

**Comment by beruic** [comment]
I originally wanted to reopen this one, but after researching I just want to leave some information, in case others have this issue.

I had the same problem.

I host in a docker image (based on `python:3.6`) through uWSGI, and the error did not occur on the development server.

The issue is triggered by special characters. In my case it's the danish letter `ø`.

First I tested in various browsers (Chrome, Firefox, Edge) on both Linux and Windows to see if there was a difference in how they treat the upload. All give the same error.

Then I turned my eye on uWSGI, and found two Stackoverflow answers on different questions ([here](https://stackoverflow.com/a/28742461/1031534) and [here](https://stackoverflow.com/a/32461966/1031534)) both indicating the same solution, namely adding

```ini
env LANG=en_US.utf8
env LC_ALL=en_US.UTF-8
env LC_LANG=en_US.UTF-8
```

to the uWSGI config.

This solved the issue for me.

**Comment by beruic** [comment]
Since my former comment seems to have disappeared in oblivion, I'd just like to notice that I fixed this on uWSGI by adding
```ini
env LANG=en_US.utf8
env LC_ALL=en_US.UTF-8
env LC_LANG=en_US.UTF-8
```
to the configuration. It is important to notice that the casing matters.

See https://stackoverflow.com/a/32461966/1031534 and https://stackoverflow.com/a/28742461/1031534
