### ISSUE TITLE
savepoint_rollback() after an IntegrityError gives TransactionManagementError

### ISSUE THREAD

**Issue by ketanbhatt** [django-import-export/django-import-export#399]
Hey, 

I noticed that if my model throws an `IntegrityError` while saving, and we do a `savepoint_rollback()` after that, it throws `TransactionManagementError`.
I investigated a little and found that in an `atomic()` block, Integrity Error causes automatic rollbacks, so calling `savepoint_rollback()` raises error.

**Comment by sergei-maertens** [comment]
+1, running into the same issue at the moment

**Comment by bmihelac** [comment]
reference: https://github.com/django-import-export/django-import-export/pull/377

**Comment by bmihelac** [comment]
This should be fixed in branch 412-drop-django-15-support

https://github.com/django-import-export/django-import-export/tree/412-drop-django-15-support

Can you please test if this works for your case?

**Comment by int-ua** [comment]
I'm getting this on `0.6.0`. The IntegrityError is raised somewhere on `init_instance` (still trying to find the exact point).

My case is having a "legal person" model that have O2O field to a Person model and a code field that is preferred for determining the right legal person. I'm trying to determine a Person by multiple fields with my custom widget and today there was two legal person rows with different codes. So it failed since I'm returning a second legal person connected to the same Person. But it doesn't raise the IntegrityError exception in my widget code for some reason. Will continue investigating it tomorrow.

**Comment by int-ua** [comment]
AFAIU the reason is that Resource.import_row doesn't account for IntegrityError possibility and [this example from Django docs](https://docs.djangoproject.com/en/1.8/topics/db/transactions/#django.db.transaction.atomic) cannot be used:

    try:
        with transaction.atomic():
            generate_relationships()
    except IntegrityError:
        handle_exception()

So we need to prevent any `savepoint_rollback` call if there was an `IntegrityError` since it has been already rolled back. Is that right?

**Comment by rhunwicks** [comment]
@bmihelac In commit:dd1c0852bac0a499693a2b31a42457e2134d266c you removed the exception handling from the call to `before_import`.

Did you mean to remove the `raise()` as well as the rollback?

Because what happens now is that if you call `import_data` with `raise_errors=True` and `before_import` has an `Exception`, then it logs the exception but doesn't raise it. So the `Resource` then carries on and tries to import all the rows in the dataset, which isn't what we want. The `after_import` call does raise errors if requested.

I will prepare an MR to add

```
            if raise_errors:
                raise
```

to the `before_import` call.
