### ISSUE TITLE
The package doesn't work with material Theme

### ISSUE THREAD

**Issue by talbenbasat** [django-import-export/django-import-export#513]
Hi,

I've used the package with the regular django theme and everything works.
However when I add the material theme -  https://github.com/viewflow/django-material/,
it doesnt appear to work.

Any guidance?

Tal

**Comment by talbenbasat** [comment]
After further investigation it appears the logic works,
However there is no export button to refer to the right url,
and the view of the export page is broken.

**Comment by thauk-copperleaf** [comment]
We had an issue when using both mptt and django-import-export, where the Import button wasn't showing up because of how the templates were structured. We made a couple of changes to facilitate having buttons for both libraries show up in #496 which is a change included with 0.5.0. Perhaps it will help?
