### ISSUE TITLE
Ids incremented twice during import

### ISSUE THREAD

**Issue by maha99tests** [django-import-export/django-import-export#560]
I'm importing a CSV file with a single new record in it, the id column is left blank.

    delete,id,name,syllabus_name,syllabus,is_generic,position
    ,,Kinematics,"Physics, VI, ICSE",3,0,0

When I import the CSV file, the preview shows the id as 9, but when the record is created, it gets an id of 10. Any reason why this is happening?

**Comment by bmihelac** [comment]
hm, import is wrapped in transaction and then rolled back for preview. What database you use? Do you have customized resource classes or settings? Can you make a simple test case?

**Comment by bmihelac** [comment]
Do you use `IMPORT_EXPORT_USE_TRANSACTIONS` setting?

**Comment by maha99tests** [comment]
I wasn't, but I adding this setting didn't fix my problem.

So in settings.py:

     IMPORT_EXPORT_USE_TRANSACTIONS=True

Here are the screenshots to show whats happening.

![screen shot 2017-01-05 at 8 49 13 pm](https://cloud.githubusercontent.com/assets/22167069/21685727/ba7edea8-d388-11e6-8b8b-3a1176916825.png)
![screen shot 2017-01-05 at 8 49 27 pm](https://cloud.githubusercontent.com/assets/22167069/21685726/ba220d18-d388-11e6-8b60-6f31032e55f6.png)

**Comment by bmihelac** [comment]
Do you have equal result when `IMPORT_EXPORT_USE_TRANSACTIONS=False`? Is `id` set in preview?

**Comment by shaggyfrog** [comment]
This is expected behaviour with Postgres. See: https://stackoverflow.com/questions/9984196/postgresql-gapless-sequences/9985219#9985219

**Comment by bmihelac** [comment]
Thanks @shaggyfrog, copied relevant text from SO:

> These only ever increase, and they're exempt from the usual transaction rollback rules to permit multiple transactions to grab new IDs at the same time. This means that if a transaction rolls back, those IDs are "thrown away"; there's no list of "free" IDs kept, just the current ID counter. Sequences are also usually incremented if the database shuts down uncleanly.

**Comment by maha99tests** [comment]
Exactly what my client needed to hear. Thank you.

**Comment by int-ua** [comment]
Workaround: This behaviour can be avoided by testing import on a separate copy of database and then importing files from CLI: #725

**Comment by photonauta35** [comment]
Same problem here. Is there any elegant solution? 

It is a little bit desaponting thing import 1000 instances and suddely get IDs from 1000  to 2000. Any operator will ask, "hey, whats happened with the right expected order?". One or two gaps is ok, but we taking about importing huge gaps, all about importing origins. 

If I deal with instances just from importing, that means the double sequential IDs for the real total one. One million instances = two milion ids. No make sense in this kind of operations. 

There is a way to get the same 'preview' sequence in the insert? Or simply ignore the sequence id in preview (dont get in that step) and makes just the final right insert?

**Comment by int-ua** [comment]
If you have time you can try adding an option to skip preview on import.

**Comment by photonauta35** [comment]
I need just skip the getting 'id' incremental process for the first time preview. Or a non pre-reverved way to deal with incremental ids. 

When you create a new object instance by django form admin, django validate your fields and after that insert the instance. Every instance is sequential, one by one, because the transation is made in one single shot. The 'validation' process is out of postgres transations. Even denying transation, the import/export get pre ids and reserve them. 

Let me sure about this: every single import process dealing with auto id field will duplicate registers? There is no way to contorn this? Every implementation of django-import-export is based on this way?

**Comment by photonauta35** [comment]
This issue seems very recurrent: 

https://github.com/django-import-export/django-import-export/issues/59
https://github.com/django-import-export/django-import-export/pull/398
https://stackoverflow.com/questions/48435549/django-import-export-specify-id-in-order-from-1
https://github.com/django-import-export/django-import-export/issues/731
https://github.com/django-import-export/django-import-export/issues/723

**Comment by jochem** [comment]
It doesn't seem to be an issue specific to PostgreSQL, see also #846 where this occurs with MySQL as well.

The whole purpose of this preview is, in my eyes, to show what things will look like after being imported. When things then turn out to be different this leads to a lot of confusion. I think either the IDs from the preview should be kept and just persisted to the database or they should not be shown in the preview at all.

There might be good reasons to be doing this (memory usage on large imports?), but I get the impression every item that gets imported is instantiated as an object twice, first for the preview (and then thrown away) and then for the actual import. If we could take the instances from the preview step along to the final step, the previewed IDs could be able to be persisted to the database, or am I missing something? Otherwise maybe it would be an option to simply build a list of generated IDs and map those to a line number in the source file?

While I'm not bothered by a gap of a few numbers in arbitrary IDs, at the moment the way this works really burns through IDs when people preview large imports.

**Comment by SilverFoxA** [comment]
+1

**Comment by SilverFoxA** [comment]
I checked this commit [d94b5f7eef2b62575b0c6be31ceba6104339fa8f](https://github.com/rhunwicks/django-import-export/commit/d94b5f7eef2b62575b0c6be31ceba6104339fa8f) from the pull request  #398 

Used the same logic and implemented the sequence reset in `before_import`

```python
class ImportPostalResources(resources.ModelResource):
    class Meta:
        model = Postal
        name = 'Import New Postal codes (Skip existing records)'
        fields = ('title', 'postal_code', 'shipping_avlb', 'country', 'state', 'city')
        skip_unchanged = True
        use_bulk = True
        force_init_instance = True
        import_id_fields = ['postal_code', ]

    def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        db_connection = self.get_db_connection_name()
        connection = connections[db_connection]
        sequence_sql = connection.ops.sequence_reset_sql(no_style(), [Postal, State, City])
        if sequence_sql:
            cursor = connection.cursor()
            try:
                for line in sequence_sql:
                    cursor.execute(line)
            finally:
                cursor.close()
```
The results that I have observed seem like a solution to reset the pk value which it was prior to the import preview.

![Screenshot 2023-01-15 at 2 44 53 PM](https://user-images.githubusercontent.com/6983070/212533045-4429b843-1908-4ef9-b21d-9e1d67b2e904.png)
![Screenshot 2023-01-15 at 2 46 06 PM](https://user-images.githubusercontent.com/6983070/212533048-52a3f2c6-42a4-44ac-b6ec-830ef85ac8c6.png)

Am I missing something here?

**Comment by matthewhegarty** [comment]
> We can also have a workaround/alternative where we allow users to not opt for preview.

There was a [PR](https://github.com/django-import-export/django-import-export/pull/1319) which was started for this, but not completed.

**Comment by matthewhegarty** [comment]
> We can also have a workaround/alternative where we allow users to not opt for preview.

This feature was added in v3.1.0 ([docs](https://django-import-export.readthedocs.io/en/stable/installation.html#import-export-skip-admin-confirm))
