### ISSUE TITLE
Having formatting or layout problem with Grappelli and Reversion

### ISSUE THREAD

**Issue by rcooke** [django-import-export/django-import-export#561]
I tried to add ExportMixin to my system.  Because I'm using 

https://github.com/etianen/django-reversion

Which uses its own custom admin, I had to use your ExportMixin.  When put second in the class list it did not seem to work.  So I put it first, as in:

`@admin.register(Parts)`
`class PartsAdmin(ExportMixin, VersionAdmin):`

Which works, but the change list view is not as shown in the sample photos. 

The "Add Parts" button used to be a large oval above the "Filter" tab. Both it and the "Export" button are simple text hyperlinks against the left hand margin.

Also, django-reversion had a "Recover Deleted" button beside the "add Parts" button, it seems to have vanished.

I'm going to start trying to untangle the various CSS logic in play here, but wanted to post first in case this is a know issue with a quick and easy fix.

Thanks in advance!

My setup:
 - Hosted on Python Anywhere
 - Django 1.10
 - Python 2.7

Cross-Posting this to all 3 libraries in use:
 
https://github.com/etianen/django-reversion/issues/615

https://github.com/sehmaschine/django-grappelli/issues/799

**Comment by wlngwang** [comment]
This happens because both `ExportMixin` and `VersionAdmin` overrides the attribute `change_list_template` which is the path of the template used by the change list view (`ExportMixin` sets `change_list_template` as `admin/import_export/change_list_export.html`, and `Reversion` sets as `reversion/change_list.html`). 

Thus based on Python MRO, whoever is put as the first in your class definition gets to use its template. 

Solution would be to write your own change list template and sets its path into the attribute `change_list_template` in your `PartsAdmin` class.

**Comment by thauk-copperleaf** [comment]
@wlngwang Thanks Will for the summary!

@rcooke There's no other real way around this, when two (or more) Django libraries both override the template attribute. Which is why you've gotten the same response from each project :)
