### ISSUE TITLE
Remove django from install_requires in setup.py

### ISSUE THREAD

**Issue by piotr-szpetkowski** [django-import-export/django-import-export#710]
Hi.
I'd like to propose to remove `django` package from `install_requires` in setup.py, because it successfully breaks package updates with `pip install -U django-import-export` by installing the latest available `django` version, which is not really desirable in most cases.

Most of mature packages e.g. djangorestframework provide empty `install_requires` with `install_requires=[]` to avoid any conflicts.

In my opinion, most users will have `django` installed before installing `django-import-export` and I assume that nobody would expect that the `django-import-export` package would work without `django`.

References:
- https://github.com/django-nose/django-nose/issues/239
- https://github.com/django-guardian/django-guardian/issues/423

**Comment by bmihelac** [comment]
Hello @piotr-szpetkowski and thanks for noticing this.

TBH I did not that upgrading would upgrade django required versions as well. This would be annoying most of the time.

cc @jdufresne - what you think about this?

https://github.com/django-import-export/django-import-export/pull/634

**Comment by jdufresne** [comment]
I would expect most projects to use a virtualenv with a `requirements.txt` file. In such a case, the Django version can be restricted with something like:

```
Django<2.0
django-import-export
```

Then:

```
$ pip install -r requirements.txt
```

In such a case, `pip` will not try to upgrade Django.

The fact remains that Django is a hard requirement of django-import-export. For that reason alone, I think it should be listed in `install_requires`.

How are you managing packages for your project such that this becomes an issue?

**Comment by manelclos** [comment]
Hi, tried these:
```
python3 -m venv venv
. venv/bin/activate
pip install -U django-import-export
```
Result: Pip installs latest available Django (2.0) and latest django-import-export. Expected. It will also install diff-match-patch, tablib, pytz, odfpy, openpyxl, unicodecsv, xlrd, xlwt and PyYAML.

It would be a nightmare to install every dependency with the correct version on that dependency tree. I want to use django-import-export, so I expect it to install anything needed.

```
python3 -m venv venv
. venv/bin/activate
pip install django==1.8.0
pip install -U django-import-export
```
Result: Pip installs django 1.8.0. Then pip install latest django-import-export, latest Django (2.0). Expected. It might be a surprise, but you asked for upgrade, consider this instead:

```
python3 -m venv venv
. venv/bin/activate
pip install django==1.8.0
pip install django-import-export
```
Result: you get django-import-export latest version and dependencies, Django version is unchanged.

```
python3 -m venv venv
. venv/bin/activate
pip install django==1.4.0
pip install -U django-import-export
```
Result: again, you ask for upgrade, you get django 2.0, if you try without upgrade option:

```
python3 -m venv venv
. venv/bin/activate
pip install django==1.4.0
pip install django-import-export
```
Result: you get Django 2.0, even when you didn't ask for it.

Seeing all the options, I'd say we keep current behaviour. If you want latest version of package X you should be aware it may require updating your old packages, including Django.

**Comment by piotr-szpetkowski** [comment]
Thank you for your valuable opinions.

For me, this issue is extremely opinion-based, however the greatest guideline I can probably point out in here is the [djangorestframework setup.py](https://github.com/encode/django-rest-framework/blob/master/setup.py#L64), which doesn't provide anything for install requirements and it simply lists out the Django as a requirement in the installation process description.

On the other hand lots of django package project maintainers decide to insert Django into install requirements, so I assume that it is a matter of interpretation of the purpose of this setting.

**Comment by jdufresne** [comment]
@manelclos Can you explain why you're installing your project's dependencies individually on the command line instead of using a `requirements.txt` file?

> It would be a nightmare to install every dependency with the correct version on that dependency tree.

`pip` handles the dependencies for you. So, I'm confused by this statement. 

If you're suggesting pinning them, using `pip freeze` or [pip-tools](https://github.com/jazzband/pip-tools) actually makes this quite easy.

**Comment by manelclos** [comment]
@jdufresne I usually do not install them manually, it was just a check of what happens on different scenarios.

The statement is about saying that I think it is right to include dependencies in the setup.py file, like we do for django (saying that 1.5 is the minimum version required), as this helps pip do the "right" thing. Like we include tablib as a requirement but there is no version constraints.

No other points, I just run those tests manually because I was curious about @piotr-szpetkowski point on the require being a problem :)

**Comment by fjsj** [comment]
For the record, [django-filter](https://github.com/carltongibson/django-filter), one of the most popular Django apps, doesn't install Django automatically as a requirement. Conversely, [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar/) does.

In the end, it's a matter of taste. But I believe not listing Django as a requirement gives flexibility for those who need to maintain old Django projects. When I want to upgrade django-import-export, I want to do `pip install -U django-import-export`, but I don't expect it to upgrade Django.

**Comment by mgrdcm** [comment]
If your project requires certain versions of Django (or any other package), it should specify those requirements in `requirements.txt` or `setup.py` or however you install dependencies.

`django-import-export` does `import` from Django packages, do Django is a _requirement_ for `django-import-export` to function, so Django **should** be listed in the requirements for `django-import-export`.  That may have other consequences when using `pip` to install packages manually, but there are ways to mitigate those.

**Comment by fjsj** [comment]
I understand that @mgrdcm. I'm talking about the steps to upgrade a package. What's your workflow when you want to upgrade a package?

Do you grab the newest version and pin on requirements manually? This works. But if want to do a `pip install -U django-import-export` and a `pip freeze` after, it will not work.

**Comment by jdufresne** [comment]
> When I want to upgrade django-import-export, I want to do pip install -U django-import-export, but I don't expect it to upgrade Django.

TBH, this feels like an issue with how `pip` works and not an error is the django-import-export list of requirements. I think it would be better to spend effort fixing the issue there instead of suggesting every Django package workaround the issue by not enumerating its requirements correctly. Here is at least one pip related issue, https://github.com/pypa/pip/pull/3194

> Do you grab the newest version and pin on requirements manually? This works. But if want to do a pip install -U django-import-export and a pip freeze after, it will not work.

Take a look at [pip-tools](https://github.com/jazzband/pip-tools). It removes the manual pinning process as well as syncs a virtualenv to a strict list of packages.

**Comment by mgrdcm** [comment]
@fjsj I use broad ranges of requirements in `setup.py` (like `Django>1.8,<=1.9`, and then in some projects a `requirements.txt` to pin to exact versions of packages for deployments.

And then to update I just do `setup.py develop`.

**Comment by bmihelac** [comment]
To summarise:

If one wants to upgrade python package without also upgrading package dependencies, manual pining in `requirements.txt` or via `pip install`  command is required, ie: 

`pip install django-import-export==0.6.1`

instead of `pip install upgrade django-import-export`.

Can we close this as obviously this is not a `django-import-export` related and majority is against the change?

**Comment by piotr-szpetkowski** [comment]
Actually, `upgrade` can be used without forced recursive upgrade. As http://pip-python3.readthedocs.io/en/latest/user_guide.html#only-if-needed-recursive-upgrade states one can provide `--upgrade-strategy` with `only-if-needed` value, which will effectively *upgrade a dependency only if it does not satisfy the new parent requirements*.

Issue resolved for me.
