### ISSUE TITLE
Problem with ForeignKeyWidget

### ISSUE THREAD

**Issue by GregKaleka** [django-import-export/django-import-export#744]
I'm following [the docs on ForeignKeyWidget](http://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.ForeignKeyWidget) very closely, and am still getting an error when uploading an Excel file. My resource looks like this:

```python
class AssignmentResource(resources.ModelResource):
	instruction_type = fields.Field(
		column_name='instruction_type',
		attribute='instruction_type',
		widget=ForeignKeyWidget(InstructionType, 'type')
	)

	class Meta:
		model = Assignment
		fields = ('instruction_type',)
```

`type` is a string field on the `InstructionType` model. When I try to upload a spreadsheet that has string values, I get this error:

`Line number: 1 - Column 'instruction_type': invalid literal for int() with base 10: 'Research'`

What am I doing wrong?

**Comment by manelclos** [comment]
can you share first two lines of the excel file? (headers + example data)

**Comment by GregKaleka** [comment]
Here's a sample:

| id        | client           | keyword  | special_instruction | instruction_type | quota | desktop quota | mobile quota | desktop pay | mobile pay |
| ------- |:-------------:| ---------- | --- | ----------- | --- | --- | --- | --- | --- |
|             |    Alfred      | assistants |       | Research  | 50  | 25 | 25 | 10 | 10 |

**Comment by manelclos** [comment]
Hi @GregKaleka, try adding the 'id' field, we will probably need to modify the documentation again ;)

Let me know if you get the same error I get: DoesNotExist

```
fields = ('id', 'instruction_type',)
```

**Comment by manelclos** [comment]
My bad with the test, after adding the 'id' field it seems to work for me.

**Comment by GregKaleka** [comment]
I'm afraid adding 'id' did not fix the problem. I'm still getting the same `invalid literal for int() with base 10` error.

I've been trying to dig through the source code to understand how the Resource attribute is used and can't quite follow how the widget is pulled in. Am I missing anything in my code above? That's the whole of my `AssignmentResource` class definition.

**Comment by GregKaleka** [comment]
I'm afraid adding 'id' did not fix the problem. I'm still getting the same `invalid literal for int() with base 10` error.

I've been trying to dig through the source code to understand how the Resource attribute is used and can't quite follow how the widget is pulled in. Am I missing anything in my code above? That's the whole of my `AssignmentResource` class definition.

**Comment by GregKaleka** [comment]
:man_facepalming:

So... I never actually added the line `resource_class = AssignmentResource` to my `AssignmentAdmin` class.

Sorry for the runaround!

**Comment by PoojaShekhar** [comment]
Please help me find a solution. I am going through the exact same issue and I have the resource class added in the admin class. Please see my code below:-
When I try importing in a table with a foreign key with datatype string, I get this error - invalid literal for int() with base 10, which I understand because the foreign key field has datatype int.

But for that before importing, do I have to edit the column in my csv with integer id values of the column being looked up for translating the foreign key value? Please share any working examples, I want to use a column of datatype string as foreign key and not the integer.

csv contains data like below:-

host_name,server_type,bay_location,ip
abc,virtual,abc,127.0.0.1


In models.py

class TypeOfServer(models.Model):
 type= models.CharField(unique=True)

class Server(models.Model)
 host_name = models.Charfield()
 server_type = 
 models.ForeignKey('TypeOfServer',to_field='type',on_delete=models.CASCADE)
 bay_location= models.Charfield()
 ip= models.Charfield()


In admin.py 

class ServerResource(resources.ModelResource):
class Meta:
  model = Server
  server_type = fields.Field(
  column_name='server_type',attribute='server_type',
  widget=ForeignKeyWidget(TypeOfServer,'type'))
  fields = ('host_name','server_type','bay_location','ip')
  skip_unchanged = True
  report_skipped = False

When I try importing the csv, it has string in the column server_type, but actually the datatype of server_type created in table in Server is int since its a foreign key. How to deal with this?

**Comment by sometimescasey** [comment]
> 🤦‍
> 
> So... I never actually added the line `resource_class = AssignmentResource` to my `AssignmentAdmin` class.
> 
> Sorry for the runaround!

I told myself I couldn't possibly have forgotten this and lo and behold I checked and...I also forgot to do this. THANK YOU!
