### ISSUE TITLE
[Question] Export FK and M2M Related fields

### ISSUE THREAD

**Issue by mykljohn** [django-import-export/django-import-export#767]
I'm having trouble getting the Related fields in FK and M2M fields to export.  

My models:  

```
class Student(models.Model):
    student = models.CharField(max_length=50, blank=False, null=False)

class Teacher(models.Model):
    teacher = models.CharField(max_length=50, blank=False, null=False)

class Course(models.Model):
    course = models.CharField(max_length=50, blank=False, null=False)

class CourseSchedule(models.Model):
    course = models.ForeignKey(Course, blank=False, null=False)
    schedule_time = models.TimeField(db_column='Schedule_Time', blank=True, null=True)
    teacher = models.ForeignKey(Teacher, blank=True, null=True)

    def __unicode__(self):
        return '%s %s %s' % (self.course, self.schedule_time.strftime('%I:%M%p'), self.teacher)

class Attendance(models.Model):
    course = models.ForeignKey(CourseSchedule, blank=False, null=False)
    date = models.DateField(db_column='Date', blank=False, null=False)
    student = models.ManyToManyField(Student, blank=True)
```

My Admin:

```
class AttendanceResource(resources.ModelResource):

    class Meta:
        model = Attendance
        fields = ('course', 'course__course__language', 'course__course__course', 'course__schedule_time', 'date', 'student' , 'student__student' )

        fields = ('course', 'course__course', 'date', 'student', 'student__student' )
        export_order = ('course__course', 'date')

```
Output:
course,date,student,course__course__language,course__course__course,course__schedule_time,course__teacher__user,student__student

3,2018-01-16,"194,195,196,197,198,199,200,201,202,203,204,205,206,208,209",INGLES,Intermediates 1,03:00PM,

Problems:
1. As you can see above, I have the unicode defined for course. but it doesn't display it, rather it displays the id and I have to use 'course__course' to display the name.  Why is this?

2. The M"M student field displays the comma delimited list, but 'student__student' is blank.  Why is this?  How can I fix it?  Cheers, Mykl

**Comment by GregKaleka** [comment]
To answer your first question, when you reference a foreign key field, it will display the id of that foreign key. That's what's in the database. There are two solutions: what you've done (referencing the attribute you want to show), or creating a custom Field using a ForeignKeyWidget. [The docs are pretty good on this point](http://django-import-export.readthedocs.io/en/stable/api_widgets.html#import_export.widgets.ForeignKeyWidget). You *must* use a ForeignKeyWidget if you want to import data using an attribute of the ForeignKey rather than the id.

You would do something like this:

```python
class AttendanceResource(resources.ModelResource):
    course_name = fields.Field(
        column_name='course',
        attribute='course',
        widget=ForeignKeyWidget(Course, 'course'))
    student_name = fields.Field(
        column_name='student',
        attribute='student',
        widget=ForeignKeyWidget(Student, 'student'))
    class Meta:
        model = Attendance
        fields = ('course', 'course_name', 'date', 'student', 'student_name' )
        export_order = ('course__course', 'date')
```

Why have you defined `fields` twice in the resource? Your output doesn't appear to match either one, and your models don't have fields that are included in your output, so I'm guessing this isn't actually what your code looks like...

As an aside, I think your attribute naming is a bit confusing. Why not give Student, Teacher, and Course a `name` attribute, rather than having the same name for the class and attributes? I think `course__name` is a lot clearer than `course__course`. Just my opinion 😄.
