### ISSUE TITLE
Example application does not work without database name

### ISSUE THREAD

**Issue by bmihelac** [django-import-export/django-import-export#864]
I just noticed that https://github.com/django-import-export/django-import-export/pull/853 causes example app to stop working.

```
ImproperlyConfigured at /admin/login/
settings.DATABASES is improperly configured. Please supply the NAME value.
```

Also, as we removed database.db so instructions for example app are not actual anymore.

**Comment by jdufresne** [comment]
IMO, it would be better to separate the example application from tests instead of overloading the two ideas. Tests should instead be a minimal amount of code & infrastructure necessary to test features. The example can more complex to allow real use of the library. This is what django-debug-toolbar does, and it works well for them. See https://github.com/jazzband/django-debug-toolbar Notice there is both an "example" and "test" directory at the top level.
