### ISSUE TITLE
Latest diff-match-patch does not work with Python 3.3 

### ISSUE THREAD

**Issue by bmihelac** [django-import-export/django-import-export#869]
Also tablib dev dropped support for Python 3.3:
https://github.com/django-import-export/django-import-export/issues/844

should we remove Python 3.3 support? This would be breaking change, so maybe we should also drop unsupported Django versions in the same time.

**Comment by mgrdcm** [comment]
I'd be in favor of that.  A breaking change, so that only [the Python versions supported by supported versions of Django](https://docs.djangoproject.com/en/2.1/faq/install/#what-python-version-can-i-use-with-django) are officially supported:

**Django version**	_Python versions_
**1.11**	_2.7, 3.4, 3.5, 3.6, 3.7 (added in 1.11.17)_
**2.0**	_3.4, 3.5, 3.6, 3.7_
**2.1, 2.2**	_3.5, 3.6, 3.7_

**Comment by andrewgy8** [comment]
I removed Python 3.3 support from the pipeline in #885

**Comment by bmihelac** [comment]
I propose removing Python 2.7, 3.3, 3.4 and Django 1.11 support with django-import-export 2.0 release.
Fixes for still supported Django/Python versions would be in branch 1.2.x.  

This will make it easier for maintaining and adding new features. What to do you think?
cc @shaggyfrog, @manelclos, @jdufresne

**Comment by jdufresne** [comment]
I think that is a wonder idea. I'm for it.

**Comment by shaggyfrog** [comment]
Agreed!

**Comment by mgrdcm** [comment]
I hate to see support for the current LTS go away, but it's hard to argue with all the cleanup that's already able to happen in https://github.com/django-import-export/django-import-export/pull/889

Has anyone started on setting up the django-import-export 1.2.x branch?  Will probably need a PR that updates the README of that branch to point out that it's bug fix only.  Maybe a definition of what will qualify for getting supported back in 1.2.x?

Thanks for your work on this project everyone - I hope to be able to get enough done on my project that's *using* this package soon so that I can start helping maintain it too :)

**Comment by yozlet** [comment]
My employer's still on Django 1.11, so I have to ask: is there a specific advantage in removing support for it, beyond "one less version to support"?

**Comment by shaggyfrog** [comment]
@yozlet It’s a good question, and it’s also the most common problem in Open Source Software, where maintainers need to carefully consider the (often free) time they give to a project given how much compensation they receive from it (often little-to-none).

Keep in mind that the older version of this library will still be compatible with Django 1.11, just that it won’t receive further updates.

If your employer is open to the idea of paying a support contract, that’s a good way to incentivize OSS projects to continue to support older versions (e.g. of Django). In this case, it might enable continuing support for 1.11 in full or in part (e.g. backporting security fixes).

**Comment by mgrdcm** [comment]
I thought the intention was already to back port security issues into 1.11?

**Comment by jdufresne** [comment]
Django 1.11 users will continue to be able to install v1.2.0 that is already on PyPI. No one will be left high and dry.

The advantages of removing support is that it makes future maintenance much easier. This is a volunteer project after all. Right now we have failing CI due to this legacy support. Some of our dependencies fail to install or run in the legacy CI environment. Rather than workaround these failures (and maintain those workarounds) it is much easier to move forward with the larger Python/Django community by dropping support for these platforms. Not only that, but the django-import-export already has lots of workarounds for older versions of Django and Python. These can now be removed creating a smaller code base that is easier to test and maintain. A smaller code base with few workarounds is much easier to adapt to new features. Some of these Python/Django versions are EOL meaning they no longer receive bug fixes including for security issues. This includes Python 3.3 and Django 1.8, 1.9, and 1.10.
