### ISSUE TITLE
How to export item from drop down in admin 

### ISSUE THREAD

**Issue by milanmaximo** [django-import-export/django-import-export#878]
I have a module Project with drop down lists, and inside of Project I have project names , like Project1, Project2, Project3 etc..
So , when I export to xls or csv , I got integer instead of names.
For example, when I export list, I got 1 or 3 or any other number instead of name Project1 or Project3 etc..
How can I solve this ?
I couldn't find any answer about that, and I would appreciate any answer.

**Comment by yozlet** [comment]
Where are the project names stored? It would help if you could paste the relevant code of your model(s).

**Comment by milanmaximo** [comment]
> Where are the project names stored? It would help if you could paste the relevant code of your model(s).

Here is my model.py and simply I just want to export this to XLS or CSV, but when I export instead of fields names I got ID of ForeignKey... only numbers.


class Furgo(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    worktime = models.CharField(max_length=50, blank=True)
    code = models.CharField(max_length=50)
    utilisation = models.ForeignKey('Utilisation', on_delete=models.CASCADE, blank=True, default=None)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, blank=True, default=None, )
    comment = RichTextField(blank='')
    comment_project = RichTextField(blank='')
    comment_equipment = RichTextField(blank='')
    comment_car = RichTextField(blank='')
#    categories = models.ManyToManyField('Category', blank=True)

    class Meta:
        verbose_name = 'furgo'
        verbose_name_plural = 'furgos'


class Utilisation(models.Model):
    name = models.CharField(max_length=30, blank=True, )

    def __str__(self):
        return self.name


class AutoCar(models.Model):
    car = models.ManyToManyField('AutoCar')
    def __str__(self):
        return self.car


class Project(models.Model):
    name = models.CharField(max_length=30, blank=True, default=None)

    def __str__(self):
        return self.name

**Comment by yozlet** [comment]
This is happening because Django Import/Export doesn't know what to do with your ForeignKey fields. By default, it will just export the content of the fields themselves (i.e. integers) rather than the records they point to.

There are a couple of ways of fixing this. (I'm not an expert, so please forgive me if they don't work as well as I'd hope.)

Both of them require you to create a a customised `ModelResource` subclass. So try creating `resources.py` and adding this:

```python
from import_export import resources, fields
from .models import Furgo

class Furgo(resources.ModelResource):
	
	class Meta:
		model = Furgo
		fields = ('title', 'date', 'author', 'worktime', 'code')
```

Some of this is explained in the [Getting Started](https://django-import-export.readthedocs.io/en/latest/getting_started.html) documentation. You also need to specify your new `Resource` class in the `FurgoAdmin` - see that page for how.

### 1. Specify a related field in the `fields`

It may be enough to add a relational field name to the `fields` attribute:

```python
	fields = ('title', 'date', 'author', 'worktime', 'code', 'project__name`)
```

Try this on its own first. It should work for exporting but not for importing.
However, if it doesn't work, or you need importing too, then try...

### 2. Use a `ForeignKey` widget

You can read more about this widget [here](https://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.ForeignKeyWidget).

```python
from import_export import resources, fields
from import_export.widgets import ForeignKeyWidget
from .models import Project

class Furgo(resources.ModelResource):
	project = fields.Field(
		attribute='project',
		column_name='project',
		widget=ForeignKeyWidget(Project, 'name')
	)

	class Meta:
		model = Furgo
		fields = ('title', 'date', 'author', 'worktime', 'code', 'project')
```

**Comment by milanmaximo** [comment]
@yozlet 
Well, If I find a way how to buy a beer of Jack Daniels to you !
You are helping a lot with this infos.

Here is complete code from resource.py 

from import_export import resources, fields
from import_export.widgets import ForeignKeyWidget
from .models import Project, Utilisation, Car, Author


class FurgoResource(resources.ModelResource):
    author = fields.Field(attribute='author', column_name='author', widget=ForeignKeyWidget(Author, 'name'))
    date = fields.Field(attribute='date', column_name='date')
    worktime = fields.Field(attribute='worktime', column_name='worktime')
    code = fields.Field(attribute='code', column_name='code')
    comment = fields.Field(attribute='comment', column_name='comment')
    comment_project = fields.Field(attribute='comment_project', column_name='comment_project')
    comment_equipment = fields.Field(attribute='comment_equipment', column_name='comment_equipment')
    comment_car = fields.Field(attribute='comment_car', column_name='comment_car')

    project = fields.Field(attribute='project', column_name='project', widget=ForeignKeyWidget(Project, 'name'))
    utilisation = fields.Field(attribute='utilisation', column_name='utilisation', widget=ForeignKeyWidget(Utilisation, 'name'))
    car = fields.Field(attribute='car', column_name='car', widget=ForeignKeyWidget(Car, 'name'))
    fields = ('author', 'date', 'worktime', 'code', 'project', 'car', 'utilisation')

class Meta:
    model = Project

**Comment by yozlet** [comment]
@milanmaximo Sorry for taking a while to respond! Did you fix it? I think I see some other changes to make if you still need help.
