### ISSUE TITLE
Pin your versions please

### ISSUE THREAD

**Issue by nagado** [django-import-export/django-import-export#923]
https://github.com/django-import-export/django-import-export/blob/f062d38922be2b4d574be562d0830e06bf8784ab/setup.py#L26

Tablib fails to install since 9 hours ago thanks to this https://github.com/kennethreitz/tablib/issues/355

**Comment by axnsan12** [comment]
It's not the job of a library to pin package versions. What would happen if library y your are also using would try to pin tablib to a different version?

**Comment by andrewgy8** [comment]
@nagado 👍  Please feel free to submit a PR to pin the version you think is appropriate.  

@axnsan12 I think its important to pin versions to guard against breaking changes.  We had this issue with tablib a few months back with a breaking version which caused trouble for our users.  That why we added them. 😉

**Comment by axnsan12** [comment]
Yes, but it's the users' responsibility to recursively pin their own versions (using poetry, pip-tools, pipenv, etc), allowing them to validate updates of any dependencies when they see fit. 

Adding unnecessary version restrictions at library levels can make dependency resolution impossible. Say you pin the tablib requirement as <0.13.0 because it supposedly doesn't install (it installs just fine for me on python 3.7 btw), and I pin it as >=0.13.0 because that version fixed xlsx exports. It's now impossible for a package manager to correctly resolve this situation, all for a needless restriction.

**Comment by andrewgy8** [comment]
Its an interesting debate, and TBH I think it can go both ways. 

However, I do strongly believe that it's the libraries responsibility to deliver as much value "out of the box" as possible. There is a way to do this to resolve the majority of dependency issues, which is to pin them to broad range of versions.  Generally, I do not feel comfortable hard pinning versions, ie. `django-import-export==1.2.0`. Instead you can do `django-import-export>=1.2.0,<2.0`. That should give you a lot of wiggle room regarding dependency conflicts.

**Comment by andrewgy8** [comment]
@nagado I have installed `django-import-export` in the last 24 hours without issue.  Do you still see an issue installing the latest version?

**Comment by andrewgy8** [comment]
Not a very straight forward topic as discussed in [this SO post](https://stackoverflow.com/a/44938662/5779280)
