### ISSUE TITLE
export button in Admin directly exporting the file in a given format

### ISSUE THREAD

**Issue by sdementen** [django-import-export/django-import-export#989]
Is it possible to have the export button exporting directly in a given format when the `get_export_formats` returns a list with one item (or maybe return not a list but directly the format) ?
i.e, in the case below, clicking the Export button would immediately download the file (instead of showing the extra screen when one has to choose a format)
```
    def get_export_formats(self):
        return [import_export.formats.base_formats.XLSX]
```
maybe there is already an option for that but I could not find it in the docs

**Comment by zhaofeng-shu33** [comment]
I do not think modification of `get_export_formats` works.

**Comment by claudep** [comment]
@bmihelac, @andrewgy8, what is this stale bot and what value does it bring to the project?

**Comment by bmihelac** [comment]
@claudep stalebot marks and closes inactive issues, helps maintainers to avoid dealing with issues that do not have enough information are invalid or no one is intereseted in resolving them. Make sense?

**Comment by claudep** [comment]
Sorry, it does not make sense to me :-) If you think an issue is invalid or does not have enough information, any triager is clever enough to close the issue explaining the reasons to the reporter. Just closing an issue because noone had time to address it for some time is not a solution in my opinion. The issue is still there, isn't it?

**Comment by iledarn** [comment]
::

 test
